### ISSUE TITLE
how ready is this project?

### ISSUE THREAD

**Issue by ccorcos** [thereactivestack/meteor-webpack#1]
I'm considering putting a bunch of time this next week converting my current project to using webpack with meteor. 

Any bugs, quirks, missing features, or anything I should be aware of / could help fix?

**Comment by eXon** [comment]
I've been testing it A LOT in the past days and in the process of switching my old projects to this. So far there is no problem. If you have any problem or idea, you can report them here or do a PR. I'll be pretty active in the upcoming weeks on this project.

**Comment by ccorcos** [comment]
sweet dude! thats awesome. where are you working? how do you have the time for this? :+1:

**Comment by eXon** [comment]
This is all done outside of my job (friday and monday off :+1: . I'm working at Cyprex and I'm lucky enough to have flexibility on that matter.

I built a pretty massive project with Meteor + Webpack + React for a consulting client of mine and I though it was a must have :) I'm on the process of converting that project with this package.

**Comment by ccorcos** [comment]
Awesome! Well I look forward to playing with it :+1:

**Comment by ccorcos** [comment]
So whats the deal with global scope? How does that work?

**Comment by eXon** [comment]
I'm guessing you're talking about Meteor global scopes? You can access them just like before. I'm not sure what the problem is.

**Comment by ccorcos** [comment]
No problem. Just curious. Can I assign to the global scope from webpack?
