### ISSUE TITLE
error when using async

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#100]
`Uncaught ReferenceError: regeneratorRuntime is not defined`
my .babelrc:
`
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    "babel-root-slash-import",
    "transform-async-to-generator"
  ]
}
`
what missing ?

**Comment by eXon** [comment]
It looks like you're missing another plugin to support generators.

**Comment by lyquocnam** [comment]
yes ! it require:
`import 'babel-polyfill';`
omg ! thanks @eXon
