### ISSUE TITLE
webpack@1.0.11 and sass@1.1.0 broke .scss import´s 

### ISSUE THREAD

**Issue by bySabi** [thereactivestack/meteor-webpack#101]
Hello @eXon.

I update a working project:

from
`webpack:webpack@1.0.8` and `webpack:sass@1.0.1`  
to
`webpack:webpack@1.0.11`and `webpack:sass@1.1.0`

Now `.scss` import´s not longer work ...
Ex:
```
import 'font-awesome/scss/font-awesome.scss';
````

Output error:
```
ERROR in ./src/App/client/index.jsx
Module not found: Error: Cannot resolve module 'undefined' in /neal-sample-meteor/src/App/client
 @ ./src/App/client/index.jsx 3:0-46

```

it was working fine with `sass` 1.0.1
 

Working branch [master](https://github.com/bySabi/neal-sample-meteor)

Updated, not working branch [webpack-1.0.11](https://github.com/bySabi/neal-sample-meteor/tree/webpack-1.0.11)

Thanks for the hard work :+1:

**Comment by eXon** [comment]
Is your webpack:css is on 1.1.0?

**Comment by bySabi** [comment]
1.0.1

**Comment by eXon** [comment]
You need to upgrade `webpack:css` to 1.1.0. I should look for a way to set dependencies for that, it's kinda tricky.

**Comment by bySabi** [comment]
it's working with css 1.1.0 adding explicitly to `packages`

packages
```
...
webpack:webpack
webpack:react
webpack:css@1.1.0
webpack:sass
```

Thanks
