### ISSUE TITLE
Blaze Support

### ISSUE THREAD

**Issue by veered** [thereactivestack/meteor-webpack#102]
Does this package support vanilla Blaze?

**Comment by eXon** [comment]
You can put .html files anywhere in your project and they are going to be valid if you have the blaze package.

**Comment by veered** [comment]
Does everything have to be structured as ES6 modules for it to work? Or is there a way for it to automatically load everything in the `client/`, `lib/` and `server/` folders?

**Comment by eXon** [comment]
For the javascript, it all start from your entry point in your package.json and you need to import them.

For your .html files, if you have the Balze package in your project, they are going to be automatically loaded. No import is required there.

**Comment by veered** [comment]
Ah OK, we still have a pretty classical Meteor project layout (no modules). How much work do you think it would be to have support for pre-module Meteor project layouts (depending on the scope I might be able to help)?

**Comment by eXon** [comment]
@veered If you make sure all your JS files are imported you should be fine. You could have a big file that import everything. You could slowly take more advantage of ES6 modules latter.

**Comment by veered** [comment]
I guess the trick will be writing a helper function that recursively imports each file with the same load order as Meteor has by default. I'll look into it and report back.

**Comment by crapthings** [comment]
change html doesn't trigger reload ?

**Comment by eXon** [comment]
Their is no special support for Blaze with Webpack ATM. If there is an awesome loader, I'll be glad to add a package for it but I'm not sure it is much needed. I'll reconsider if a lot of people want it.
