### ISSUE TITLE
JS file not change: The following modules couldn't be hot updated

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#103]
i try to change container (mantra) js file, and this warning.
browser not change like css or component jsx file (without stateless).
F5 on browser for changes.

have any options for this ?

```
[HMR] bundle rebuilt in 625ms
process-update.js?b5f7:27 [HMR] Checking for updates on the server...
process-update.js?b5f7:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js?b5f7:89 [HMR]  - ./client/modules/admin/containers/Products.js
```

**Comment by eXon** [comment]
You might need to add your own code to support hot module replacement. 

[You can read more about it here.](https://webpack.github.io/docs/hot-module-replacement.html)

**Comment by lyquocnam** [comment]
[sample code](mantra-sample-blog-app/client/modules/core/containers/post.js)
change anything in this js file and this warning will show:
`
[HMR] bundle rebuilt in 625ms
process-update.js?b5f7:27 [HMR] Checking for updates on the server...
process-update.js?b5f7:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js?b5f7:89 [HMR]  - ./client/modules/admin/containers/Products.js
`
press F5 on browser will change...
the same using with stateless component (not yet support).

**Comment by eXon** [comment]
HMR support for mantra-core could be very much be added, but it would need to be within the mantra-core codebase.
