### ISSUE TITLE
Problems cloning the repo in Windows

### ISSUE THREAD

**Issue by jptissot** [thereactivestack/meteor-webpack#105]
I am having trouble cloning the repository in windows. Here are the error messages recieved: 

![image](https://cloud.githubusercontent.com/assets/4681586/13781697/a0be4a62-ea9a-11e5-86b8-3e56d595a73b.png)

Resetting the repository fails as well.

![image](https://cloud.githubusercontent.com/assets/4681586/13781753/cd45121e-ea9a-11e5-9d0f-1ab5af2e9958.png)

**Comment by eXon** [comment]
This is an issue with Git / GitHub I'm not sure has a solution. The webpack:webpack folder would be webpack_webpack on Windows but because I'm on Mac, you can't checkout this. I'm not sure what we can do about it.

**Comment by bySabi** [comment]
@eXon maybe you must put `.npm` folder on .gitignore

**Comment by eXon** [comment]
@bySabi This is unfortunally the opposite of [what the readme says](https://github.com/thereactivestack/meteor-webpack/tree/master/packages/webpack/.npm/plugin/webpack:webpack) :(

**Comment by bySabi** [comment]
@eXon I don´t get it! :-(

Don´t undestand this README. I though that meteor rebuild packages `.npm` artifacts at each build.

**Comment by bySabi** [comment]
I got it now!
:-)

**Comment by jptissot** [comment]
Seems to be some kind of strange meteor bug. I used my linux VM to get that PR in but wanted to let you know of the issue.

**Comment by eXon** [comment]
Maybe I can rename webpac:webpack folder by webpack_webpack. I'm pretty sure it would be the name on Windows and it would work on both platform.
