### ISSUE TITLE
Use hash '#' in devtool sourcemaps

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-webpack#106]
Hey - as per https://github.com/webpack/webpack/issues/91#issuecomment-191763512, you should probably replace `cheap-source-map` with `#cheap-source-map` :)

**Comment by eXon** [comment]
If you use the last version, the default is to # :)

**Comment by dbismut** [comment]
Are you sure? I'm using a fork of your package and I'm patching it from time to time with your updates, and I had to add a hash [here](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/WebpackCompiler.js#L400) and [there](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/WebpackCompiler.js#L398) ?

**Comment by eXon** [comment]
Have you updated to the last version with webpack 1.12.14?

# is the default now and if I look at my own source map it seems correct.

**Comment by dbismut** [comment]
Ok well forget it, must be me. Not sure what's happening. I'm using Chrome Version 50.0.2661.26 beta and it throws multiple warnings.

**Comment by dbismut** [comment]
My mistake, not sure what was happening with my version of webpack, you were right @eXon. Closing the issue.
