### ISSUE TITLE
Production Deployment CSS Modules

### ISSUE THREAD

**Issue by bearcanrun** [thereactivestack/meteor-webpack#107]
Trying to deploy to DO with Mupx or Galaxy. Using Meteor 1.21, built on kickstart-meteor-react-router.
Using webpack:
webpack:assets@1.0.0
webpack:core-config@1.0.0
webpack:css@1.1.0
webpack:less@1.0.0
webpack:npmworkaround@1.0.0
webpack:react@1.1.3
webpack:reload@1.0.0
webpack:webpack@1.0.11

This is all in my webpack.json:
{
  "root": "src",
  "devServer": {
    "host": "localhost"
  },
  "css.module": true
}

Getting errors:
While processing files with webpack:webpack (for target web.browser):
src/client.js: ./src/ProducerApp/client/css/ProducerApp.import.css
Module parse failed:
/Business/land-of-here/loh/src/ProducerApp/client/css/ProducerApp.import.css
Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.
| :local(.checked) {
|   text-decoration: line-through;
| }
@ ./src/ProducerApp/client/css/ProducerApp.import.css 4:14-51
src/client.js: ./src/TodoApp/client/css/TodoApp.import.css
Module parse failed:
/Business/land-of-here/loh/src/TodoApp/client/css/TodoApp.import.css Line 1:
Unexpected token :
You may need an appropriate loader to handle this file type.
| :local(.checked) {
|   text-decoration: line-through;
| }
@ ./src/TodoApp/client/css/TodoApp.import.css 4:14-47
src/client.js: ./src/TodoApp/client/css/TodoApp.import.css

App runs fine in development, just trying to figure out how to deploy in a production environment. Suggestions of something I'm missing or where to look? Looked at all documentation for CSS Loader and compared to your webpack:css source.

**Comment by eXon** [comment]
You should not use `css.module` but:
```json
{
  "css": {
    "module": true
  }
}
```

**Comment by bearcanrun** [comment]
Ok, just to make sure, I forked your [kickstart-meteor-react-router](https://github.com/bearcanrun/kickstart-meteor-react-router), updated to latest and tried to to deploy to Galaxy and to DO with mupx and got similar errors as original post.

**Comment by bearcanrun** [comment]
Working on trying to narrow down the problem. Removed usage of CSS modules to confirm problem is directly related to them. Success. App deploys to Galaxy and DO via mupx without problems.Will now try to re-integrate in the simplest manner.

**Comment by mydearxym** [comment]
@bearcanrun  is this problem solved ?

**Comment by bearcanrun** [comment]
@mydearxym I haven't found anything yet. Similar to  #110, but downgrading my webpack to 1.0.8 didn't  change the same errors as I show above for me. I've been ignoring the use of css modules for the time being and getting the rest of my app working.

**Comment by eXon** [comment]
Should be fixed in last version. Let me know if it works!
