### ISSUE TITLE
Automate meteor packages and ES6 modules bridging

### ISSUE THREAD

**Issue by mquandalle** [thereactivestack/meteor-webpack#11]
Currently we have to define a list of global variables we want to import in the `externals` option of the Webpack configuration. For large apps that use a lot of packages it can be a little bit painful and repetitive (and every time you add or remove a package or that a package changes its exports we have to edit this file again).

Since Meteor already maintains a list of used packages and their respective exported symbols under the `Package` object it would be great if we could create the bridge automatically so we can

```es6
import $ from 'jquery';
import { Match, check } from 'check';
```

without configuring anything.

If I understand correctly Webpack resolves dependency at bundle time while this package object seems to be only (easily) accessible at runtime which may be an issue, but I still think this is a feature to consider.

**Comment by eXon** [comment]
I understand your pain, I have the same and came to this simple conclusion: just use the global variables. They are still there and available even if you don't import. Maybe I should just remove them from the kickstart projects. You don't need to add everything to `externals`. You can use every Meteor global variables anywhere.

I'm not sure I like it but it might be better than having a huge list of externals.

**Comment by eXon** [comment]
I've changed the config to only include react and react-router because they are regular NPM modules and I want to make sure the Meteor version is used and it is not included twice. I think it's overkill to import everything there. Meteor global variables are all availables everywhere anyway.

**Comment by eXon** [comment]
It has been added to the 0.4.0 release :) Thanks for the idea!

If a package export ReactRouterSSR, it will be available through:

```javascript
import ReactRouterSSR from 'ReactRouterSSR';
// or...
import ReactRouterSSR from 'react-router-ssr';
```
