### ISSUE TITLE
Wrong line numbers (again)

### ISSUE THREAD

**Issue by thesunny** [thereactivestack/meteor-webpack#111]
I'm seeing the wrong line numbers when an error is thrown.

I think it is related to this old issue that was solved before:

https://github.com/thereactivestack/meteor-webpack/issues/4

**Comment by thesunny** [comment]
Note: A temporary fix to this is to create a `webpack.conf.js` file in the root directory of the project.

```
module.exports = {
  devtool: 'cheap-module-eval-source-map'
}
```

**Comment by eXon** [comment]
I would need to compare the speed of `cheap-module-eval-source-map` but

**Comment by jbbr** [comment]
According to http://webpack.github.io/docs/configuration.html#devtool rebuild speed of `cheap-module-eval-source-map` should be equal to currently used `cheap-eval-source-map`.
Only first build is slower.

**Comment by eXon** [comment]
This has been fixed and the default settings should have correct line numbers. Thanks for reporting!
