### ISSUE TITLE
cannot resolve module 'fibers'

### ISSUE THREAD

**Issue by rkstar** [thereactivestack/meteor-webpack#115]
i'm trying to import `fibers/future` like this:
```
import Future from 'fibers/future'
```
so that i can `return future.wait()` and use it inside my `Meteor.methods` functions.  i've had to resort to `Npm.require('fibers/future')` but i thought that i should be able to use it just like any other npm package, no?

**Comment by swennemans** [comment]
I'm not sure how the library is build, but did you try:
`
import { future } from 'fibers'`
`
Did you try other npm packages?

**Comment by MasterAM** [comment]
I was just trying to do the same and got the following error after installing `fibers` with `npm`:

```
   While processing files with webpack:webpack (for target os.linux.x86_64):
   src/server.js: ./~/fibers/fibers.js
   Module parse failed: /home/.../node_modules/fibers/fibers.js Line 2:
   Illegal return statement
   You may need an appropriate loader to handle this file type.
   | if (process.fiberLib) {
   |     return module.exports = process.fiberLib;
   | }
   | var fs = require('fs'), path = require('path');
   @ ./~/fibers/future.js 2:12-31
```

This is the case for various attempts to import, including the lines in the previous messages.

The `Npm.require` workaround seems to do the trick (for now, using Meteor v1.2.1).
Other npm packages work well.

**Comment by lyquocnam** [comment]
why not use babel-preset-stage-1 with await/async ? i think it will better. i using that for my project

**Comment by eXon** [comment]
@MasterAM What version of fibers are you using? Meteor is still on Node.js 0.10.40 so you might have some issues because of this.

**Comment by MasterAM** [comment]
@eXon, I think that you are right about this. I ran into a couple more issues when building or deploying an app.

I was using Node v5.6.0 when building, so `less` modules were not bundled properly.

I then switched to v0.10.4x and it seems to be working. I did not get back to `fibers` yet (as the workaround was successful).

@lyquocnam, the reason for requiring it in the first place is that some legacy code uses it and I don't have the time to adapt it to the new APIs.

**Comment by lucidprogrammer** [comment]
if you use meteor npm instead of npm these issues should go away (1.3)

**Comment by eXon** [comment]
I don,t think there is anything to fix here. Let me know if you think otherwise.

**Comment by rkstar** [comment]
so the solution is to use `Npm.require('fibers/future')` then?  i was really hoping to get rid of all that business.

if i'm missing something, please throw an example down in here that'd be cool.

**Comment by eXon** [comment]
We don't have much control over that unfortunally. Let me know if you have a solution.

**Comment by fawad1985** [comment]
Meteor version 1.3 and up

$ Meteor npm install --save fibers

Then in your code, lets import the 'Future' variable

import { Future } from 'fibers/future';
