### ISSUE TITLE
Issue with css modules

### ISSUE THREAD

**Issue by dubvfan87** [thereactivestack/meteor-webpack#117]
I'm trying to get the react-flexbox-grid & flexboxgrid packages working with meteor-webpack. It needs to import as css module from /node_modules/flexboxgrid. They suggest adding something like this to webpack.conf.js, but I am having trouble doing this with meteor-webpack's webpack.json file. I have tried to add the block below to my project as proper json by adding quotes around the regex's - but I cannot get it to load. What am I missing here?

```
"module": {
  "loaders": [
     {
       "test": /\.css$/,
       "loader": "style!css?modules",
       "include": "/flexboxgrid/"
     }
    ]
}
```

here is my webpack.json file

```
{
  "css": {
    "module": true
  },
  "module": {
    "loaders": [
      {
        "test": "/\\.css$/",
        "loader": "style!css?modules",
        "include": "/flexboxgrid/"
      }
    ]
  }
}
```

**Comment by lyquocnam** [comment]
try to import:
`import 'flexboxgrid/flexboxgrid.css';`
make sure install **webpack:css** package.

**Comment by dubvfan87** [comment]
Wow, that worked. I've been stuck on this for a few days now. The webpack config can be a bit tricky for n00bs. Thank you.

**Comment by lyquocnam** [comment]
happy for solved your problem :D

**Comment by infacq** [comment]
i'm trying to get cssLoader to work. How to make it work?

**Comment by lyquocnam** [comment]
are you sure installed webpack:css atmosphere package ?
and install npm deps after add meteor package:
`npm install`

**Comment by rafaelcorreiapoli** [comment]
It's not working for me.
