### ISSUE TITLE
Server restart on client file change?

### ISSUE THREAD

**Issue by D1no** [thereactivestack/meteor-webpack#119]
I am not sure, but I have the feeling that when ever any file is touched, also the meteor server is restarted? In the console it shows:
```
=> Meteor server restarted
```

**Comment by eXon** [comment]
Do you have your client-code within a client folder?

**Comment by D1no** [comment]
www.github.com/d1no/todos
Everything is in the imports folder and I have set webstorm entry to the client/main.js file

It's a fork of the official todos app. Adapted in structure - maybe you see what I mean, if you add webpack and change a file in the imports folder that belongs to the client

**Comment by D1no** [comment]
Latest 1.3-rc.8

**Comment by D1no** [comment]
Okay, the current build process still looks for client folders. Even inside the imports folder. Otherwise restarts also the server. That sucks.

https://forums.meteor.com/t/react-hotloading-in-native-meteor-is-ready-i-e-no-webpack/17523/81?u=dinos

**Comment by eXon** [comment]
Thanks for reporting that to Meteor. The client folder is unfortunally the easiest way to control the server restart for now :(

**Comment by eXon** [comment]
If webpack was able to trigger the client restart and the server restart by himself, it would be a lot easier to manage. Right now, the plugin has 0 control for that

**Comment by D1no** [comment]
Mh, can you add that statement to the issue at meteor. I think it's
important to signal this escape hatch for plugin authors. Beeing able to
turn off the watcher with a flag and trigger client / server restarts via a
hook
On Mi., 23. März 2016 at 16:18, Benoit Tremblay <notifications@github.com>
wrote:

> If webpack was able to trigger the client restart and the server restart
> by himself, it would be a lot easier to manage. Right now, the plugin has 0
> control for that
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/meteor-webpack/issues/119#issuecomment-200390415>
>
-- 
Send from my Smartphone. Beware spelling and grammar.
-- 
Dino Scheidt
Tel.: +49 (0) 151 2265 6200
Luxemburger Str. 118 | 50939 Cologne | Germany
//Connect with me via LinkedIn.dino-scheidt.de

**Comment by eXon** [comment]
I'll close this but I'll follow the issue on meteor. Thanks for reporting!
