### ISSUE TITLE
noParse - how to configure in webpack:webpack

### ISSUE THREAD

**Issue by lucidprogrammer** [thereactivestack/meteor-webpack#122]
how do I pass a noParse to the webpack.json ?

(I need to ignore certain paths of pre-built js etc) FYI, to solve the following type of error, google search suggests to provide noParse regex in webpack. 

Any inputs ? Tks in advance

`WARNING in ./~/google-libphonenumber/dist/browser/libphonenumber.js
Critical dependencies:
1:487-494 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/google-libphonenumber/dist/browser/libphonenumber.js 1:487-494`
_

**Comment by eXon** [comment]
Right now there is nothing to support the noParse option. It might be great to be able to add files or folders like this:

```json
{
  "noParse": [
    "google-libphonenumber/dist"
  ]
}
```

Would it fix your problem?

**Comment by lucidprogrammer** [comment]
Yes, that will be great @exon

**Comment by lucidprogrammer** [comment]
Thats regex/some pattern rigjt?

**Comment by eXon** [comment]
@lucidprogrammer If your path match the value, it will be a noParse. No need to be an exact match.

Maybe we could support glob syntax (example: *.lib.js)

**Comment by lucidprogrammer** [comment]
That will be great

**Comment by lucidprogrammer** [comment]
@eXon Providing webpack.json as follows.
`{
  "devServer": { "host": "localhost"},
  "css" : {"module":true},
  "noParse": [
    "google-libphonenumber/dist"
  ],
  "postcss": [
    ["autoprefixer", { "browser": "last 2 versions" }]
  ]
}`

webpack versions in the versions file in meteor

`webpack:assets@1.0.1
webpack:core-config@1.0.1
webpack:css@1.1.1
webpack:html@1.0.2
webpack:npmworkaround@1.0.0
webpack:postcss@1.1.1
webpack:react@1.1.4
webpack:reload@1.0.0
webpack:sass@1.1.1
webpack:webpack@1.0.12`

Still getting the same error as follows
`WARNING in ./~/google-libphonenumber/dist/browser/libphonenumber.js
Critical dependencies:
1:487-494 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/google-libphonenumber/dist/browser/libphonenumber.js 1:487-494`

I tried giving ./~/google-libphonenumber/dist/browser/libphonenumber.js also in noParse, no luck. Am I missing something

**Comment by lucidprogrammer** [comment]
It works with the following. 
`{
  "devServer": { "host": "localhost"},
  "css" : {"module":true},
  "noParse": [
    "libphonenumber.js"
  ],
  "postcss": [
    ["autoprefixer", { "browser": "last 2 versions" }]
  ]
}
`

**Comment by eXon** [comment]
It might be because of the way I'm constructing the regex. I'll take a look.
