### ISSUE TITLE
Issue deploying to heroku (#2)

### ISSUE THREAD

**Issue by albertmatyi** [thereactivestack/meteor-webpack#125]
# Setup

## `.meteor/release`

    METEOR@1.3-beta.16

## `.meteor/packages`

    # Base
        meteor-base             # Packages every Meteor app needs to have
        mobile-experience       # Packages for a great mobile UX
    # Build
        standard-minifiers      # JS/CSS minifiers run for production mode
        es5-shim                # ECMAScript 5 compatibility for older browsers.
        # ecmascript              # Enable ECMAScript2015+ syntax in app code
        webpack:webpack
        webpack:react
        webpack:less
        # webpack:assets
    #UI
        # React
            # react-runtime # using npm version instead
            # jsx
            react-meteor-data
    # Services
        accounts-password
    # FE Services
        rzymek:moment
        less
    # BE Services
           mongo                   # The database Meteor supports right now
    # To throw out (maybe)
        insecure                # Allow all DB writes from clients (for prototyping)
        session                 # Client-side reactive dictionary for your app
        tracker                 # Meteor's client-side reactive programming library

## `package.json`

{
      "name": "...",
      "description": "...",
      "version": "1.0.0",
      "main": "server/main.js",
      "browser": "client/main.js",
      "private": true,
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "engines": {
        "node": "5.9.0",
        "npm": "3.8.3"
      },
      "dependencies": {
        "material-ui": "^0.15.0-alpha.2",
        "react": "^0.14.7",
        "react-dom": "^0.14.7",
        "react-router": "^2.0.1",
        "react-tap-event-plugin": "^0.2.2"
      },
      "devDependencies": {
        "babel": "^6.3.26",
        "babel-core": "^6.3.26",
        "babel-loader": "^6.2.0",
        "babel-plugin-add-module-exports": "^0.1.2",
        "babel-plugin-react-transform": "^2.0.0",
        "babel-plugin-transform-decorators-legacy": "^1.3.2",
        "babel-plugin-transform-runtime": "^6.6.0",
        "babel-preset-es2015": "^6.3.13",
        "babel-preset-react": "^6.3.13",
        "babel-preset-stage-0": "^6.3.13",
        "css-loader": "^0.23.0",
        "eslint": "^2.4.0",
        "expose-loader": "^0.7.1",
        "extract-text-webpack-plugin": "^0.9.1",
        "file-loader": "^0.8.5",
        "less": "^2.3.1",
        "less-loader": "^2.2.2",
        "react-transform-catch-errors": "^1.0.0",
        "react-transform-hmr": "^1.0.1",
        "redbox-react": "^1.2.0",
        "style-loader": "^0.13.0",
        "url-loader": "^0.5.7",
        "webpack": "^1.12.9",
        "webpack-hot-middleware": "^2.4.1"
      }
    }

# What works

1. Local Run / Build from scratch
1. Build via Jenkins docker

# What does not work

1. `git push heroku master` with buildpack `https://github.com/AdmitHub/meteor-buildpack-horse`

# Error

    remote: -----> Building Meteor with ROOT_URL: https://funbees.herokuapp.com
    remote: Errors prevented bundling:
    remote: While processing files with webpack:webpack (for target web.browser):
    remote: client/main.js: ./client/routes.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/core-js/object/get-prototype-of' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/core-js/object/get-prototype-of in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/routes.js 7:22-78
    remote: client/main.js: ./client/routes.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/classCallCheck' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/classCallCheck in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/routes.js 11:23-70
    remote: client/main.js: ./client/routes.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/createClass' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/createClass in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/routes.js 15:20-64
    remote: client/main.js: ./client/routes.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/possibleConstructorReturn' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/possibleConstructorReturn in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/routes.js 19:34-92
    remote: client/main.js: ./client/routes.js
    remote: Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits'
    remote: in /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/inherits in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/routes.js 23:17-58
    remote: client/main.js: ./client/app.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/core-js/object/get-prototype-of' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/core-js/object/get-prototype-of in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/app.js 7:22-78
    remote: client/main.js: ./client/app.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/classCallCheck' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/classCallCheck in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/app.js 11:23-70
    remote: client/main.js: ./client/app.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/createClass' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/createClass in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/app.js 15:20-64
    remote: client/main.js: ./client/app.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/possibleConstructorReturn' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/possibleConstructorReturn in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/app.js 19:34-92
    remote: client/main.js: ./client/app.js
    remote: Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits'
    remote: in /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: resolve module babel-runtime/helpers/inherits in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/app.js 23:17-58
    remote: client/main.js: ./client/views/login/login.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/core-js/object/get-prototype-of' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: resolve module babel-runtime/core-js/object/get-prototype-of in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/views/login/login.js 7:22-78
    remote: client/main.js: ./client/views/login/login.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/classCallCheck' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: resolve module babel-runtime/helpers/classCallCheck in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/views/login/login.js 11:23-70
    remote: client/main.js: ./client/views/login/login.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/createClass' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: resolve module babel-runtime/helpers/createClass in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/views/login/login.js 15:20-64
    remote: client/main.js: ./client/views/login/login.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/possibleConstructorReturn' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: resolve module babel-runtime/helpers/possibleConstructorReturn in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/views/login/login.js 19:34-92
    remote: client/main.js: ./client/views/login/login.js
    remote: Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits'
    remote: in /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: resolve module babel-runtime/helpers/inherits in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/views/login
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/views/login/login.js 23:17-58
    remote: client/main.js: ./client/elements/logo/logo.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/core-js/object/get-prototype-of' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: resolve module babel-runtime/core-js/object/get-prototype-of in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/elements/logo/logo.js 8:22-78
    remote: client/main.js: ./client/elements/logo/logo.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/classCallCheck' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: resolve module babel-runtime/helpers/classCallCheck in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/elements/logo/logo.js 12:23-70
    remote: client/main.js: ./client/elements/logo/logo.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/createClass' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: resolve module babel-runtime/helpers/createClass in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/elements/logo/logo.js 16:20-64
    remote: client/main.js: ./client/elements/logo/logo.js
    remote: Module not found: Error: Cannot resolve module
    remote: 'babel-runtime/helpers/possibleConstructorReturn' in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: resolve module babel-runtime/helpers/possibleConstructorReturn in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/elements/logo/logo.js 20:34-92
    remote: client/main.js: ./client/elements/logo/logo.js
    remote: Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits'
    remote: in /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: resolve module babel-runtime/helpers/inherits in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/client/elements/logo
    remote: looking for modules in
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules
    remote: /tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime doesn't
    remote: exist (module as directory)
    remote: [/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/babel-runtime]
    remote: @ ./client/elements/logo/logo.js 24:17-58
    remote: 
    remote: While processing files with webpack:webpack (for target os.linux.x86_64):
    remote: fs.js:666:18: ENOENT, no such file or directory
    remote: '/tmp/build_f221ef43e0a65cb2a18ed51ab56b6143/node_modules/bowser/'
    remote: at Object.fs.readdirSync (fs.js:666:18)
    remote: at addNpmPackage (plugin/WebpackCompiler.js:646:21)
    remote: at readPackageJson (plugin/WebpackCompiler.js:638:9)
    remote: at addNpmPackage (plugin/WebpackCompiler.js:660:3)
    remote: at plugin/WebpackCompiler.js:650:7
    remote: at Array.forEach (native)
    remote: at addNpmPackage (plugin/WebpackCompiler.js:648:9)
    remote: at plugin/WebpackCompiler.js:650:7
    remote: at Array.forEach (native)
    remote: at addNpmPackage (plugin/WebpackCompiler.js:648:9)
    remote: at readPackageJson (plugin/WebpackCompiler.js:638:9)
    remote: at compile (plugin/WebpackCompiler.js:580:9)
    remote: at runWebpack (plugin/WebpackCompiler.js:256:5)
    remote: at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:103:5)
    remote: 
    remote: 
    remote: 
    remote:  !     Push rejected, failed to compile Node.js app
    remote: 
    remote: Verifying deploy...
    remote: 
    remote: !	Push rejected to

# If anyone figured it out how to fix it please comment - even if it is related to another tool (which I could not prove)

**Comment by eXon** [comment]
Closing this but let me know if you're still having troubles with the last version.
