### ISSUE TITLE
webpack:coffeescript - Coffeescript files requiring meteor restart to update

### ISSUE THREAD

**Issue by TheAncientGoat** [thereactivestack/meteor-webpack#128]
I'm not sure what I've done wrong here - but after using the kickstart-mantrajs-webpack project, adding coffeescript seems to break the webpack build process somehow, necessitating restarting the meteor process to get the code to update (refreshing the page does nothing).

I'm running Meteor 1.3, using ecmascript 2015 modules; haven't modified the .babelrc or webpack.json

**Comment by eXon** [comment]
What file extension are you using for your cofeescript files?
