### ISSUE TITLE
Using NPM packages on the server

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack#13]
I noticed that we still have to use `Meteor.npmRequire` or `Npm.require` instead of just `require` to use NPM packages on the server, is this intentional?

**Comment by eXon** [comment]
There is two types of NPM packages you might need:

1. Packages that we can bundle with your code. Something that doesn't need to run inside Node.js.
2. Packages that needs to be run within Node.js (anything that needs to access your file system on the server for example).

I am actually working on using webpack.packages.json. It will be modules that is bundled with your app. The packages.json file, it will send the NPM module to the server.

It's coming soon :)

**Comment by rclai** [comment]
Ah okay cool.

**Comment by rclai** [comment]
Wait, I see there's `react-mixin` but you were able to use it on the client, how did you do that?

**Comment by eXon** [comment]
Currently anything you add to packages.json, you can use it with import. In case of react-mixin, it is working both on client and on the server so it doesn't matter.

You can't import something like phantomjs because it has to run on the server as an example.

**Comment by eXon** [comment]
You can now use webpack.packages.json for NPM packages that are not run by the server. You can see my update on the Meteor forums: https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264/124?u=benoitt
