### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by joetidee** [thereactivestack/meteor-webpack#131]
Just installed the package and received this error on my app which is running Meteor 1.2.1:

 While determining active plugins:
   error: conflict: two packages included in the app (jsx and webpack:webpack) are both trying to handle *.jsx

**Comment by eXon** [comment]
You can't use Webpack and the `jsx` package. It might be because you are using the `react` package, which infer `jsx`. If it's the case, remove the `react` package and add `react-runtime` and `react-meteor-data`. It should fix your problem.
