### ISSUE TITLE
Update to documentation on Atmosphere

### ISSUE THREAD

**Issue by joetidee** [thereactivestack/meteor-webpack#132]
ON your Atmosphere page, you say "Your entry files are defined within your package.json" - what are 'entry files' and which package.json is it referring to (the one for the webpack:webpack package, or the one in the root of my meteor app) ?

**Comment by eXon** [comment]
Your entry points are defined by the `main` and `client` config on your package.json file:

```json
{
  "name": "project-name",
  "main": "src/server.js",
  "client": "src/client.js",
}
```

I can certainly make that a little more clear in the doc.

**Comment by joetidee** [comment]
But where is the package.json file located? Also, can you define 'entry points', for example, in my Meteor app I have startup.js in both client and server folders (which are the first script run my Meteor) - are these entry points?

**Comment by infacq** [comment]
for all npm project, normally npm will require you to have `package.json`

**Comment by eXon** [comment]
Let me know if you can't make it work but I'm guessing no action is required here.
