### ISSUE TITLE
[1.0.12] React is not defined

### ISSUE THREAD

**Issue by rravikot** [thereactivestack/meteor-webpack#137]
It seems that #73 is still not working after the update and after installing webpack:react. Just wanted to reopen the issue to get this resolved.

**Comment by hlandao** [comment]
+1

**Comment by lyquocnam** [comment]
+1

**Comment by gothicn** [comment]
+1

**Comment by rkstar** [comment]
to all you +1-ers ... there is a `Subscribe` button to the right of the comments thread.  click it and you'll get notified if anything happens on this issue. adding **+1** just adds noise to a thread.

<img width="520" alt="screen shot 2016-04-04 at 2 19 24 am" src="https://cloud.githubusercontent.com/assets/651566/14239647/d7ec2f10-fa0b-11e5-86bc-db9460c13933.png">

**Comment by lyquocnam** [comment]
+1 for author know how many people like this... you think +1..ers have more money man ? ^^

**Comment by eXon** [comment]
Update `webpack:react` and `webpack:webpack` and it should work fine now with Meteor 1.3 and React on NPM :)
