### ISSUE TITLE
how do I use css loader

### ISSUE THREAD

**Issue by infacq** [thereactivestack/meteor-webpack#138]
I want to get this working

```js
import theme from 'theme.css';
<Autosuggest theme={theme} ... />
```

**Comment by lyquocnam** [comment]
this men: https://github.com/thereactivestack/meteor-webpack/issues/117

**Comment by infacq** [comment]
do i have to specify `include`? I have many other?

```js
{
  "css": {
    "module": true
  },
  "module": {
    "loaders": [
      {
        "test": "/\\.css$/",
        "loader": "style!css?modules",
        "include": "/flexboxgrid/"
      }
    ]
  }
}
```

**Comment by lyquocnam** [comment]
i no need this code:
```
 "module": {
    "loaders": [
      {
        "test": "/\\.css$/",
        "loader": "style!css?modules",
        "include": "/flexboxgrid/"
      }
    ]
  }
```
just import and make sure right path to package.
ussually:
`import theme from 'npmPackageName/dist-folder/theme.css';`

**Comment by infacq** [comment]
do I have to put the `webpack.config.js`?

**Comment by lyquocnam** [comment]
demo project here: 
https://github.com/mantrajs/kickstart-mantrajs-webpack

**Comment by eXon** [comment]
You can just follow the examples.
