### ISSUE TITLE
TypeScript - forced transpileOnly for ts-loader

### ISSUE THREAD

**Issue by mzugn** [thereactivestack/meteor-webpack#139]
This shouldn't be forced in webpack:typescript:

`tsConfig.transpileOnly = true;`

Not running the typechecks kind of defeats the purpose of using TypeScript, so I think an option for this should be added in `webpack.json`, or better yet, it could get the value from `tsconfig.json`.
In addition to `compilerOptions`, people might want to set options for ts-loader specifically too.

I will likely have time in the following days to make these updates to `webpack:typescript` and I'll submit a PR then, if you're busy with other parts of the package.

**Comment by eXon** [comment]
Just removed that line. I haven't used a lot of TypeScript yet and don't fully understand all those settings. Thank you for pointing this out!
