### ISSUE TITLE
Triggering rebuilds with modules not yet imported

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack#14]
In Andy's boilerplate, whenever you create a module that has not yet been imported, Meteor doesn't trigger a rebuild, but on yours, it does.

**Comment by eXon** [comment]
It is not Webpack that triggers the rebuild but Meteor. Andy's boilerplate is not using the Meteor build system. I have no control over watched files :(

Let me know if you think there is a better soluton.

**Comment by rclai** [comment]
Aww :cry: okay, no problem.

Come to think of it, what happens if you put the files inside a folder prefixed with a dot, Meteor will ignore those, but will your Webpack package ignore it?

**Comment by rclai** [comment]
In the simple kickstarter project, I named the `modules` folder `.modules` and changed the config file to resolve root to the `.modules` folder, and looks like your plugin IS able to watch changes on anything in that folder, as well as hot module reload, which is awesome! In addition, when I create a new file there, Meteor doesn't trigger a rebuild until I actually import it!

This isn't perfect, but I feel no qualms about naming a folder with a dot, so this is still golden.
