### ISSUE TITLE
Windows - Please avoid using invalid filenames in this package

### ISSUE THREAD

**Issue by lucidprogrammer** [thereactivestack/meteor-webpack#142]
Can't do much with this in windows, to test or try. For example, if you put packages/webpack it will fail as in windows, there is no way to create a folder with name webpack:webpack

**Comment by lucidprogrammer** [comment]
I assume this is not an issue with this repo per se. webpack:webpack link does not work in standard windows. Not sure if you can fix with naming packages without the colon syntax?

**Comment by leoetlino** [comment]
They're not "invalid", just not handled correctly by Windows. Using a better development environment will fix this; if you're stuck with Windows, but Windows 10, you might be able to use [the Ubuntu on Win10 env that was recently announced](http://arstechnica.com/information-technology/2016/03/ubuntus-bash-and-linux-command-line-coming-to-windows-10/) (in the future).

**Comment by eXon** [comment]
Please report this to Meteor. I have no control over this :/
