### ISSUE TITLE
Possible to *not* use Webpack on the server?

### ISSUE THREAD

**Issue by leoetlino** [thereactivestack/meteor-webpack#143]
Is it possible to *not* use Webpack for the server-side code? Webpack is failing with native Node modules that I import from my server code, such as mmmagic, protobuf, etc.

```
   server/index.js: ./~/mmmagic/lib/index.js
   Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/magic in
   /home/.../apps/node_modules/mmmagic/lib
   resolve file
   /home/.../apps/node_modules/mmmagic/build/Release/magic doesn't exist
   /home/.../apps/node_modules/mmmagic/build/Release/magic.js doesn't exist
```

Of course, I would still like to be able to use Webpack for the client-side code. Thank you.

**Comment by leoetlino** [comment]
Actually, that would bring other problems, I guess. Is there a way to make it work with native Node modules?

**Comment by eXon** [comment]
It should not fail if you're using the last version.

**Comment by eXon** [comment]
Actually the code is targetting Node.js for the server-side code. It shouldn't bring any problem even with things like mmmagic

**Comment by leoetlino** [comment]
Okay, I'll test again with the latest version when I can. Thanks.
