### ISSUE TITLE
Errors prevented bundling: (mac osx -> os.linux.x86_64)

### ISSUE THREAD

**Issue by rkstar** [thereactivestack/meteor-webpack#144]
```
Errors prevented bundling:                    
While linking the program:                    
error: this app is not compatible with architecture 'os.linux.x86_64'
```

[this issue](https://github.com/meteor/meteor/issues/6537) on the meteor repo describes what's happening, but i'm putting it here because when i searched for `fsEvents` in my node_modules dir i found a bunch of them in the webpack module dir.

any chance these can be non-binary dependencies?

**Comment by rkstar** [comment]
after further investigation i found this to be the offending file/package:
```
node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node
```

i don't know if this can be used without this binary `fse.node` file, but if it can, that would solve the build problem we're having with meteor 1.3

**Comment by rkstar** [comment]
so meteor 1.3.2_2 is out, but i'm still getting build errors when i try to deploy with `mupx`.  here is the error:
```
While processing files with webpack:webpack (for target os.linux.x86_64):
fs.js:666:18: ENOENT, no such file or directory
'/Users/rkstar/dev/projects/backlot/src/node_modules/bowser/'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget
(packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

i've grepped my code as well as the `node_modules/` dir for this `bowser` reference, but there is none.  i don't know where this is coming from or how to debug it.  

any help at all with this would be appreciated.

**Comment by lyquocnam** [comment]
i think this work, tested by me https://github.com/thereactivestack/meteor-webpack/issues/150

**Comment by eXon** [comment]
You should clean your node_modules folder, update all your Meteor package and `npm install` again. I'm on mac and everything works perfectly fine.
