### ISSUE TITLE
import meteor and meteor packages

### ISSUE THREAD

**Issue by jeffshaver** [thereactivestack/meteor-webpack#146]
Is there a reason you can't do `import {Meteor} from 'meteor/meteor'` like is in the docs? Or for that fact `import <anything> from 'meteor/<anything>'`? Kind of confused how to get this working.

**Comment by dpacmittal** [comment]
Do you have modules package installed?

**Comment by jeffshaver** [comment]
Yeah I installed it and that didn't fix the issue.

**Comment by eXon** [comment]
you should be able to do `import { Meteor } from 'meteor/meteor';`. Are you still having the problem?

**Comment by eimhin** [comment]
@eXon Just tried version 1.1.1 and the import error is still happening

**Comment by genyded** [comment]
+1 - I have tried all the kickstarts (without any changes) and they all fail with:

```
ERROR in ./src/client.js
Module parse failed: \projects\kickstart-met
eor-react-flowrouter-master\src\client.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { FlowRouter } from 'meteor/meteorhacks:flow-router';
|
| import 'TodoApp/client';
 @ multi main
```

Also updated to webpack 1,1.1 and it made no difference. I also tried the mantra kickstart and same thing.

**Comment by eXon** [comment]
I'm not sure what you guys are doing but I clone kickstart-flowrouter, I update all packages and do the import and everything works as expected. What version of Meteor are you using?

**Comment by genyded** [comment]
Hey Benoit... I've tried the Meteor version that comes with the repos and various 1.3.x and get the same with them all. I don't see how it could matter, but I am on Windows. I can download any of the kick starts, run meteor update and npm install, then Meteor and everyone ones dies with the error. I've spent days trying to figure this out to no avail. I have to abandon webpack for the time being in order to try and meet my deadlines, but raw Meteor reloads are SO slow, I am hosed either way ;-)

Not sure what else to try. I have been using the kickstarts for months without issue so I have no idea why this is happening all of a sudden with the latest versions.

**Comment by genyded** [comment]
I cloned the flow router kick start into a clean directory again just to be sure and here is the output after the initial Meteor update:

```
Changes to your project's package version selections from updating package
versions:

react-meteor-data            upgraded from 0.2.4 to 0.2.9
standard-minifiers           removed from your project
tmeasday:check-npm-versions  added, version 0.2.0
webpack:assets               upgraded from 1.0.0 to 1.0.1
webpack:core-config          upgraded from 1.0.0 to 1.0.1
webpack:css                  upgraded from 1.1.0 to 1.1.1
webpack:react                upgraded from 1.1.3 to 1.2.0
webpack:webpack              upgraded from 1.0.10 to 1.1.1


The following top-level dependencies were not updated to the very latest
version available:
 * react-runtime 0.14.3 (15.0.1 is available)
 * thereactivestack:blazetoreact 0.1.5 (1.0.1 is available)
```
If I then try to update react-runtime or thereactivestack:blazetoreact by name - I get:

`The specified packages are at their latest compatible versions.`

So then I run`meteor' and it updates package.json. The I run 'npm install' and it completes without error. The I run `meteor` again and:

```
ERROR in ./src/client.js
Module parse failed: C:\Users\genyd\AppData\Local\.meteor\projects\kickstart-met
eor-react-flowrouter-master\src\client.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { FlowRouter } from 'meteor/meteorhacks:flow-router';
|
| import 'TodoApp/client';
 @ multi main
```
Same with react router kick start or mantra kick start. I did notice (not sure if it matters) that even after all the updates, the meteor packages file still has React hardcoded @14.3...

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

es5-shim                # ECMAScript 5 compatibility for older browsers.

react-runtime@=0.14.3
react-meteor-data
thereactivestack:blazetoreact

webpack:webpack
webpack:react
webpack:css
webpack:assets

accounts-ui
accounts-password
blaze-html-templates
meteorhacks:flow-router
kadira:react-layout
standard-minifier-css
standard-minifier-js
```

**Comment by eXon** [comment]
@genyded Meteor is a real bitch about versioning. Seriously. Try to remove and re-add `thereactivestack:blazetoreact` and it should work.
