### ISSUE TITLE
SASS loader does not support .sass files with indented syntax. Please help!

### ISSUE THREAD

**Issue by thesunny** [thereactivestack/meteor-webpack#147]
Sorry for the pleading in the title.

I've been trying to configure this myself using `webpack.conf.js` for many hours over many days now but not succeeding.

Is there any way somebody could add support for `.sass` files into webpack:sass or show me how to do it myself using `webpack.conf.js`? I would be very grateful.

I got this far (below) but it's not clear to me that it is even using the config at all...

```javascript
module.exports = {
  loaders: [
    {
      test: /\.sass$/,
      loader: '!style!css!sass?indentedSyntax!'
      // loaders: ['style', 'css?sourceMap', 'sass?indentedSyntax']
    }
  ],
  extensions: ['.sass']
}
```

Gives me an error like this all the time...

```
ERROR in ./client/css/bookbar.sass
Module parse failed: /Users/sunnyhirai/Projects/knocket/client/css/bookbar.sass Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @import variables.scss
|
| .bookbar
 @ ./client/app/bookbar/bookbar.jsx 25:0-33
```

**Comment by bensventures** [comment]
I am by no means an expert in webpack but I believe the `extensions` configuration should go into a `resolve` attribute. (http://webpack.github.io/docs/configuration.html#resolve-extensions)

For example here is my webpack.conf where I define the extensions:

```
module.exports = {
    resolve: {
        modulesDirectories: [
            "node_modules",
            "modules",
            "modules/client"
        ],
        extensions: ['', '.js', '.jsx', '.json', '.scss']
    }
};
```
Maybe you could try this?

**Comment by infacq** [comment]
no luck. Is there any other workaround

```js
{
  "root": "src",
  "devServer": {
    "host": "localhost"
  },
  "sass": {
    "module": true,
    "includePaths": ["./node_modules"]
  },
  "css": {
    "module": true
  },
  "module": {
    "loaders": [
      {
        "test": "/\\.css$/",
        "loader": "style!css?importLoaders=1!autoprefixer",
        "include": [
        	"./node_modules",
        	"./src/Apps/client/css/"
        ]
      }
    ]
  },
  "resolve": {
        "modulesDirectories": [
            "node_modules"
        ],
        "extensions": [".sass"]
  }
}
```

**Comment by eXon** [comment]
I'll look to add the setting and add the missing extension. Let me test this and I'll let you know.

**Comment by eXon** [comment]
I just added the support for indentedSyntax out of the box. Will be released in the next version (today)

**Comment by infacq** [comment]
am still getting this error

```bash
ERROR in ./~/bulma/bulma.sass
Module parse failed: /Users/bonnierotten/Documents/sewa/src/node_modules/bulma/bulma.sass Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @charset "utf-8"
|
```

**Comment by eXon** [comment]
There is no new release yet. Will be dome very soon.

**Comment by mikeerickson** [comment]
@eXon Is this supported out of the box yet?
