### ISSUE TITLE
Plz update webpack to latest 1.13

### ISSUE THREAD

**Issue by bySabi** [thereactivestack/meteor-webpack#148]
Hi @eXon update webpack to latest 1.13.

I hope SourceMap bug will fixed: https://github.com/webpack/webpack/issues/91

**Comment by priezz** [comment]
Why not to use Webpack 2.x? Is it really hard to switch to it?

**Comment by lyquocnam** [comment]
good news here https://github.com/thereactivestack/meteor-webpack/issues/150

**Comment by eXon** [comment]
Done :)
