### ISSUE TITLE
Fails to resolve path to package.json in npm module

### ISSUE THREAD

**Issue by gsabran** [thereactivestack/meteor-webpack#149]
Hi!
I think I got the main config right. The build is failing while importing a npm package and trying to load its `package.json`:

Somewhere I have:
`import juice from 'juice';`

And this npm package loads its config with `var packageJson = require('./package');`

Webpack fails to resolve this path with:

    Errors prevented startup:                  
       While processing files with webpack:webpack (for target os.osx.x86_64):
       src/server.js: ./~/juice/index.js
       Module not found: Error: Cannot resolve 'file' or 'directory' ./package in
       pathToProject/node_modules/juice
       resolve file
       pathToProject/node_modules/juice/package doesn't exist
       pathToProject/node_modules/juice/package.js doesn't exist
       pathToProject/node_modules/juice/package.jsx doesn't exist
       pathToProject/node_modules/juice/package.css doesn't exist
       pathToProject/node_modules/juice/package.less doesn't exist
       resolve directory
       pathToProject/node_modules/juice/package doesn't exist (directory default file)
       pathToProject/node_modules/juice/package/package.json doesn't exist (directory description
       file)
       [pathToProject/node_modules/juice/package]
       [pathToProject/node_modules/juice/package.js]
       [pathToProject/node_modules/juice/package.jsx]
       [pathToProject/node_modules/juice/package.css]
       [pathToProject/node_modules/juice/package.less]
       @ ./~/juice/index.js 15:18-38

It seems that webpack looks at `/package/package.json` instead of `/package.json`.

**Comment by gsabran** [comment]
This is enough to reproduce the bug: https://github.com/gsabran/kickstart-meteor-react-flowrouter/commit/7249fe4a92429b0cff9ef8152559dc323b1f403b

**Comment by lyquocnam** [comment]
try here men https://github.com/thereactivestack/meteor-webpack/issues/150

**Comment by eXon** [comment]
Are you trying to use this client-side?

**Comment by gsabran** [comment]
no server side

**Comment by gsabran** [comment]
Let me know if you are able to reproduce the issue that appears with this simple commit: https://github.com/gsabran/kickstart-meteor-react-flowrouter/commit/7249fe4a92429b0cff9ef8152559dc323b1f403b

**Comment by eXon** [comment]
Are you having the same error if you are using Meteor without Webpack?

**Comment by eXon** [comment]
You just have to add the `webpack:json` loader and it will fix the error. However, it seems like there is another one unrelated to this issue.

I've added the package as a required dependency to webpack:webpack. Everyone should have the json loader anyways.

**Comment by gsabran** [comment]
thanks!
