### ISSUE TITLE
"Dropping unreachable code" warnings when building

### ISSUE THREAD

**Issue by nickw** [thereactivestack/meteor-webpack#15]
I attempted to deploy to Galaxy and got a blank page. To debug, I ran a `meteor build .` locally and started poking around. In `bundle/programs/server/assets/app/webpack.stats.json` I see dozens of "Dropping unreachable code" warnings. It looks like anything we're trying to `import` in our app code isn't being bundled - hence the blank screen on Galaxy.

Attached is a truncated screenshots of the warnings (it was too big for a gist):

<img width="1128" alt="screen shot 2015-10-22 at 1 25 53 pm" src="https://cloud.githubusercontent.com/assets/3907/10677345/98a776ec-78c0-11e5-9631-e74d4ee4e144.png">

**Comment by eXon** [comment]
Yes we should definitively remove the warnigns from this generated file.

When you deploy on galaxy, are you using meteor deploy? 

Webpack isn't detecting that command as a production mode build (I'll fix that ASAP). I think this should fix your problem.

**Comment by nickw** [comment]
Yeah, using `meteor deploy`. Do I just need to prepend it with `NODE_ENV=production` ?

**Comment by eXon** [comment]
Yes it would work until I make the fix.

**Comment by nickw** [comment]
:+1: that worked. Thanks!
