### ISSUE TITLE
Good news - webpack can use with kickstart normally !

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#150]
hi everyone, i tried with new project and install webpack package, that **still error on build**.
but i work best on kickstart: https://github.com/thereactivestack/kickstart-meteor-react-flowrouter.

this work good on **webpack 1.13** too.

you can use this and wait for mr @eXon back (he has some private project, may be so long) !

**Comment by rkstar** [comment]
are you saying to just run `npm update` for webpack inside the project dir?  i don't understand what you're saying here.

**Comment by lyquocnam** [comment]
year, you can use kickstart project and update to webpack 1.13, it work !

**Comment by gsabran** [comment]
webpack 1.13 doesn't resolve https://github.com/thereactivestack/meteor-webpack/issues/149

**Comment by mzugn** [comment]
Thanks for mentioning this, but sadly the update doesn't resolve any of the issues (exception in build, still need that try-catch for that referenced in the other issue; compile time is still incredibly long (7 minutes for me, it's not a kickstart project), and it takes a long time to recompile in dev mode when I change server files.

**Comment by lyquocnam** [comment]
@gsabran @mzugn  try use kickstart ?
i dont know how, but it work fine, on build and webpack 1.13 too.
i clone kickstart
```
meteor update --release 1.3.2.2
npm install
meteor
//or
meteor build ../bin
```

**Comment by priezz** [comment]
Webpack 2.x is working as well. Put in your `package.json`:
```
...
    "extract-text-webpack-plugin": "git://github.com/RahavLussato/extract-text-webpack-plugin.git",
    "webpack": "^2.1.0-beta.5",
...
```

**Comment by john-osullivan** [comment]
Are you sure that it's actually working correctly and not that the baseline `kickstart-meteor-react-router` repo just doesn't contain code which exhibits the bug?  Seems like the error people encountered in https://github.com/thereactivestack/meteor-webpack/issues/133 (which I'm currently running into as well) was a fundamental issue with how the `addNpmPackage` worked.  Maybe the issue just isn't presenting itself with the basic configuration, even if adding more complexity would make it pop up.

**Comment by lyquocnam** [comment]
my project work fine !
http://www.quanlynhatro.com
you can contact me, i can help with teamviewer.
my facebook: 
`https://www.facebook.com/lynam.chibi`

**Comment by lyquocnam** [comment]
@priezz webpack 2.x may be error when deploy production.

**Comment by priezz** [comment]
Production build works fine for me as well.

P.S. Did not try it with react router, just with flowrouter (with and w/o SSR).






On Sun, Apr 24, 2016 at 11:01 AM -0700, "Lý Quốc Nam" <notifications@github.com> wrote:












@priezz webpack 2.x may be error when deploy production.

**Comment by lyquocnam** [comment]
i use with flowrouter and not try with react-router yet

**Comment by menelike** [comment]
I had to disable uglify to get things working https://github.com/thereactivestack/meteor-webpack/issues/140#issuecomment-214775111

**Comment by john-osullivan** [comment]
In my case, I was getting an error saying that the package `esprima-fb` couldn't be found.  Somebody in another thread said they'd had the same issue and solved it by running `npm i esprima-fb`.  I had to do the same thing for another package afterwards, but now it's all working!  I'm using react-router-ssr, so I can confirm that it's operating correctly with that configuration.

**Comment by eXon** [comment]
Last version work perfectly with React 15 and Meteor 1.3 (react-router-ssr has been updated too). Let me know if I'm missing something here.
