### ISSUE TITLE
fs namespace is messed up when using collectionFS

### ISSUE THREAD

**Issue by minfawang** [thereactivestack/meteor-webpack#151]
I'm trying to use some node modules that use `fs` to read/write files internally, and got a bunch of errors. So I did a console log like below:
~~~javascript
import fs from 'fs';
console.log(fs);
~~~

And I see the following in the console:
~~~shell
{
  Store: { GridFS: [Function], FileSystem: [Function], S3: [Function]  },
  AccessPoint: {},
  Utility: {
    ...
  },
  ...
}
~~~

Looks like the `FS` variable from the `collectionFS` package was printed out here. I think it's a bug to be fixed. Any help is appreciated!

**Comment by eXon** [comment]
You need to be more specific on how to replicate

**Comment by minfawang** [comment]
Here is the reproduction repo:
https://github.com/minfawang/webpack-fs-error-reproduce

Basically I just cloned the kickstarter repo, updated all the packages with `meteor update`. And then install `cfs:standard-packages` and `cfs:filesystem`. You can review the console statement and see the object is not exported from the `fs` module.

Could you please re-open this issue?

**Comment by minfawang** [comment]
@eXon Just saw your activity in the last minute. Hence ping you here.
I have updated with a reproduce repo. Could you please re-open this issue?

**Comment by eXon** [comment]
I'll try to take a look real quick.

**Comment by minfawang** [comment]
Thank you so much!!

**Comment by minfawang** [comment]
And to provide a little hint:

The package `meteor/cfs:base-package` exports the `FS` object, which I believe is the cause of the bug.

**Comment by eXon** [comment]
This has been fixed for the next release :)

**Comment by minfawang** [comment]
Awwwsome!
