### ISSUE TITLE
build too large file size

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#153]
currently, meteor build, it will take about 11mb bundled file.
with webpack, it will take 50mb bundled file. ( impossible ).
can we optimize this ?

**Comment by eXon** [comment]
This is because the Webpack build will bundle the node modules it needs to run on the server. I'll take a look if we can stop doing that now that 1.3 has native NPM support.

**Comment by eXon** [comment]
It looks like Meteor is the cause of that big bundle. They are bundling EVERYTHING, including devDependencies. They should not. I'll open an issue about it.

**Comment by eXon** [comment]
You can follow the official issue on Meteor: https://github.com/meteor/meteor/issues/6836

**Comment by eXon** [comment]
In webpack:webpack 1.1.1 I've removed the bundling of node_modules. However, this doesn't seem to be the biggest factor. We'll need to wait for meteor.

**Comment by lyquocnam** [comment]
glad see you again @eXon

**Comment by eXon** [comment]
Doesn't look like the Meteor team want to do anything about it. You can do `npm prune --production` before your deployment if you want a leaner package. I certainly don't like this idea but at least it is one.
