### ISSUE TITLE
build time so long

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#154]
if code in server or both, meteor webpack will rebuild and take long time.
in client code, all fine !

**Comment by gunn** [comment]
This is because there's no hot module reloading for the server so it has to restart each time a change is made. I don't think meteor-webpack can change that. Although a hot reloading server would be very cool...

**Comment by menelike** [comment]
this could also be related to https://github.com/thereactivestack/meteor-webpack/issues/153#issuecomment-216038131

**Comment by eXon** [comment]
@lyquocnam I think this is because of Meteor. I've seen some complains about that in their bug issues. There is nothing we can really fix within Webpack scope. Let me know if you think otherwise.
