### ISSUE TITLE
update webpack/package.json to webpack@1.13

### ISSUE THREAD

**Issue by menelike** [thereactivestack/meteor-webpack#155]
I think [this](https://github.com/thereactivestack/meteor-webpack/blob/879da61eb11f04cd150feaba26b41e38923b2dee/packages/webpack/package.js#l25) line should point to webpack v1.13

**Comment by swennemans** [comment]
Would be great. Hopefully fixes sourcemap output as discussed here: https://github.com/webpack/webpack/issues/91

**Comment by menelike** [comment]
@swennemans this should have already been fixed with the current v1.1.1?
This issue is rather a "cosmetic" issue, webpack v1.13 is in charge due to other parts of code, no matter what version is specified in this package.json. I can confirm that sourcemaps are currently working.

**Comment by bySabi** [comment]
I solved SourceMap problems adding `"devtool": "dev"` to `webpack.json`

my current webpack.json
```
{
  "root": "src",
  "devServer": {
    "host": "localhost"
  },
  "sass": {
    "includePaths": ["./node_modules"]
  },
  "devtool": "eval"
}
```

**Comment by eXon** [comment]
This one wasn't fix thank you for pointing it out!
