### ISSUE TITLE
Fail to deploy after upgrade to 1.1.1

### ISSUE THREAD

**Issue by minfawang** [thereactivestack/meteor-webpack#156]
First thanks for the work of fixing the issue of npm dependencies. However, after I'm upgrading the package (meteor-webpack) to the latest version, the deployment fails with the following non-constructive error message:
~~~shell
DEPLOY_HOSTNAME=galaxy.meteor.com meteor deploy --settings settings.json my.website.com
Error deploying application: Internal error
~~~

I'm certain it's caused by this upgrade because the only thing I did was to run `meteor update`, and only this package was updated. When I reseted back to the last commit, the deployment works again.

Does anyone encounter the same issue?

**Comment by minfawang** [comment]
Note: I'm using the latest version of meteor 1.3.2.4

**Comment by eXon** [comment]
Is this still hapenning?

**Comment by minfawang** [comment]
It's fixed. Thank you!
