### ISSUE TITLE
Meteor build doesn't change .js and .css files -> Infinite reload after deploy

### ISSUE THREAD

**Issue by tokn136** [thereactivestack/meteor-webpack#158]
When running:  `meteor build ` the created bundle contains a main .js and .css file. Usually these file names change every time one runs `meteor build`. 
However, since upgrading to 1.3 these file names remain.
The problem here is that the browsers caches these files and after deploying the browser keeps reloading infinitely unless you disable the cache.
Has anyone else experienced the same behavior?
Does anyone know how the file names are generated?
Any help is greatly appreciated.

**Comment by eXon** [comment]
Are you experiencing the same problem with a non-Webpack project?
