### ISSUE TITLE
Dynamic webpack configuration

### ISSUE THREAD

**Issue by jdanilov** [thereactivestack/meteor-webpack#159]
Hi! I'd like to specify different entry points (browser and main) based on environment settings. That is to use HMR in debug and code splitting in production mode (since HMR doesn't work for me when code splitting with asynch module imports are in place).

I found no straightforward way of specifying different entry points on a kickstart react router configuration since both package and webpack are plain json files except substitution via external script.

Is there a good way of doing so or am I missing something?

**Comment by eXon** [comment]
I'm not sure to understand what you're looking for but here is a few key things to know:

 - You can specify a different entry file for the server and the client using your package.json (https://github.com/thereactivestack/kickstart-meteor-react-router/blob/master/package.json#L6-L7)
 - You can use `Meteor.isClient` and `Meteor.isServer` the same way you would with Meteor and it will only available there
 - If you want to do code splitting, you can't do it by specifying multiple chunks. There is no way Meteor would know how to handle that. However, you can use `require.ensure` (see https://webpack.github.io/docs/code-splitting.html)
 - You probably only want some stuff to work only in production. You can use `if (process.NODE_ENV === 'production')` for that.

**Comment by jdanilov** [comment]
Sorry for not making it clear. Yes, I understand these points. The issue I'm having is if I use require.ensure, HMR doesn't work since it does not recognize React Components in asynch chunked code.

Thus I'd like to specify two sets of client (browser) entry points: one for development without code splittig but with HMR, another for production with code splitting.

Is there a way of doing so? Or am I wrong in saying code splitting via require.ensure breaks HMR and I'm missing the point?

**Comment by eXon** [comment]
You don't need different entry points. You just need to do something like that:

```javascript
if (Meteor.isServer || process.env.NODE_ENV === 'production') {
 // Use require.ensure here
} else {
  // Use regular require here
}
```

Different entry points for this doesn't really make sense.

**Comment by laurentpayot** [comment]
Can we use `Meteor.isProduction` the same way as `process.env.NODE_ENV === 'production'` or are there some differences between the two expressions?

**Comment by jdanilov** [comment]
Thanks @eXon, will try that. I believe this could be closed

**Comment by eXon** [comment]
@laurentpayot It would be really easy to add. I wasn't aware of that one. I guess it would work but Webpack would not optimize it.

**Comment by laurentpayot** [comment]
@eXon Do you mean webpack will only remove/add blocks of code if they are wrapped in a `process.env.NODE_ENV === 'production'` condition?

**Comment by eXon** [comment]
Meteor.isProduction is now supported if you update to the last version of `webpack:webpack` :)
