### ISSUE TITLE
Need webpack:livescript package

### ISSUE THREAD

**Issue by focused** [thereactivestack/meteor-webpack#160]
I don't use coffescript or babel, livescript gives me more power, how can i use livescript with webpack and meteor now?

**Comment by focused** [comment]
I have two questions more:
1. Why I need to put all the code to the src dir?
2. Can I have entry points with `*.ls` (not *.js) extensions?

**Comment by eXon** [comment]
Yes you can. It would be very easy to create a package for that (anybody can create a plugin). I'll take a look at this one.

Yes entry points can be .ls and the src dir isn't required. You can use whatever folder structure you would like.

**Comment by focused** [comment]
I can take a coffeescript plugin as the base, change it and make PR, but i'm newbie with meteor, so i have no idea how to test it locally on my mac.

If I place entries inside standard meteor server and client folders would meteor engine watch them? Should we avoid that?

**Comment by focused** [comment]
I made PR #161

**Comment by eXon** [comment]
It has been published. Thank you so much for the PR!
