### ISSUE TITLE
meteor test not working with Vue

### ISSUE THREAD

**Issue by laurentpayot** [thereactivestack/meteor-webpack#162]
I added a `foo.tests.coffee` file with a trivial mocha test `chai.assert.isTrue(true)`.
When I do `meteor test --driver-package practicalmeteor:mocha` I get:
```
$ meteor test --driver-package practicalmeteor:mocha
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20160513-13:22:19.808(2)? (STDERR)           
W20160513-13:22:19.917(2)? (STDERR) /tmp/meteor-test-runcws6x1/.meteor/local/build/programs/server/app/server.js:12096
W20160513-13:22:19.918(2)? (STDERR)         install(Vue, options_) {                                          // 6
W20160513-13:22:19.918(2)? (STDERR)                ^
W20160513-13:22:19.918(2)? (STDERR) SyntaxError: Unexpected token (
W20160513-13:22:19.918(2)? (STDERR)     at /tmp/meteor-test-runcws6x1/.meteor/local/build/programs/server/boot.js:278:30
W20160513-13:22:19.918(2)? (STDERR)     at Array.forEach (native)
W20160513-13:22:19.918(2)? (STDERR)     at Function._.each._.forEach (/home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160513-13:22:19.918(2)? (STDERR)     at /tmp/meteor-test-runcws6x1/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8  
```
```
$ meteor list | grep webpack
webpack:coffeescript                1.0.1  Integrate CoffeeScript with Webpack
webpack:jade                        1.0.1  Integrate Jade import (.jade) with...
webpack:less                        1.1.1  Integrate LESS import with Webpack
webpack:postcss                     1.1.1  Integrate PostCSS (.css) import wi...
webpack:vue                         1.0.2  Integrate Vue.js with Webpack
webpack:webpack                     1.3.0  Seamlessly integrate Webpack to im...
```
Note that I also have a `tests/` folder with my _Chimp_ tests, but it should be ignored by `meteor tests`.

**Comment by eXon** [comment]
I'm not very familiar with Vue.js. I'm not sure why this is crashing in test mode. Do you have a repo with the bug I can test?

**Comment by laurentpayot** [comment]
Here it is: https://github.com/laurentpayot/meteor-webpack-vue-tests

**Comment by eXon** [comment]
@laurentpayot it seems like the `vue-meteor` package is not properly built. It also fails in proudction.

It is because the library is not compatible with older version of javascript. Everyone is not on Node 4+ and the Meteor Node version doesn't support the syntax. Maybe you could [report this to the author](https://github.com/almini/vue-meteor).

**Comment by laurentpayot** [comment]
@eXon unfortunately I'm not using `vue-meteor` in the reproduction repo. Do you think _webpack:vue_ is using an incompatible version of Node?

**Comment by eXon** [comment]
I don't think it has anything to do with Vue itself.

You're using `vue-meteor`in your example: https://github.com/laurentpayot/meteor-webpack-vue-tests/blob/master/meteor/src/app/client/routes.coffee#L3

**Comment by laurentpayot** [comment]
D'oh! I forgot  to remove it from the package list. I updated my repo. No more Vue error now. I'm going to open an issue on `vue-meteor`. Thanks @eXon :+1:

**Comment by eXon** [comment]
Awesome :)
