### ISSUE TITLE
Is there a reason source file directory cannot be called 'imports'? (Or webpack crashes with ReferenceError: WebpackDevServerConfig is not defined)

### ISSUE THREAD

**Issue by alesn** [thereactivestack/meteor-webpack#163]
Hi, I've been using webpack:webpack for some time in my project already with previous versions of webpack:webpack and meteor. I've had to stay at METEOR@1.3.1 and webpack:webpack@1.0.12 because uprading to Meteor 1.3.2.4 and the more recent versions of webpack always crashed right as the application starts with the error:
reload.js:23 Uncaught ReferenceError: __WebpackDevServerConfig__ is not defined

As the problem remained there through several new upgrades of webpack packages I spent quite a bit of time investigating the cause and found that this error is thrown when the source directory of the project, where imports are stored is called 'imports'. This was working perfectly fine in the above mentioned versions and the previous ones but since then it just throws the above mentioned error. So, I would like to know if the imports directory cannot be called 'imports' with the latest versions of webpack and meteor and the directory must be renamed to something else. Or if the problem can be fixed in webpack:webpack so this works keeping the directory name. To reproduce the problem, just use the kickstart projects and change the source directory to 'imports' (updating the references in webpack.json and package.json) and it will throw this error when you try to access the app. If the imports directory must not be called 'imports' with webpack:webpack, I think this should be clearly mentioned in the documentation

**Comment by eXon** [comment]
I've made some tests and it turns out only the entry files cannot be within an imports directory. I'll see what I can do to fix that.

**Comment by eXon** [comment]
Just keep your entry points out of an import folder and you're going to be fined. You can move client.js / server.js in the root directory instead and fix the path in the package.json and it will work as expected. I've added a notice in the readme.

**Comment by alesn** [comment]
This works. Thank you ;)
