### ISSUE TITLE
Can't load modules from meteor shell?

### ISSUE THREAD

**Issue by gsabran** [thereactivestack/meteor-webpack#165]
I used to be able to load modules from meteor shell like `const {Items} = require('./collections.js');`
With `webpack:webpack` that seems to now fail and I get:

```
$ meteor shell
> require('./src/server_and_client/collections.js')
Error: Cannot find module './src/server_and_client/collections.js'
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
    at [object Object]:1:-61
    at Script.(anonymous function) [as runInThisContext] (vm.js:41:22)
    at /Users/me/projectName/.meteor/local/build/programs/server/shell-server.js:366:27
    at /Users/me/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/meteor-promise/fiber_pool.js:33:40
```

I'm sure there is a file at `./src/server_and_client/collections.js`

**Comment by eXon** [comment]
You can't because Meteor has no clue the file is existing. Webpack takes care of bundling it. It is how the Meteor build system works unfortunally.

**Comment by gsabran** [comment]
Ok. Thanks for the clarification. So is there still a way to access things like collections from the shell? Or is it something that's not possible with webpack? If so, what workflow do you recommend?

To clarify things a bit, let's say that my main entry is `'./server.js` which is:
```javascript
import {Items} from './collections.js'
console.log('Items', !!Items);
```

That works, and it prints `Items true` as excepted, but from the shell, `Items` is not defined, and I can't load `./collections.js` correct?

**Comment by gsabran** [comment]
I'd like to fix that with a PR on the read me once it's clear what's the best way to get around this issue, can we reopen the issue until then to keep the discussion opened? (I know closing issues feels great!)

**Comment by eXon** [comment]
@gsabran If you have a way to fix this it would be cool. AFAIK the shell will have problems understanding all the webpack specific stuff
