### ISSUE TITLE
Can't use require on the server side

### ISSUE THREAD

**Issue by gsabran** [thereactivestack/meteor-webpack#166]
I can't dynamically load files on the server:
```javascript
// server.js
import 'TodoApp/server';

require.ensure(['TodoApp/client/components/TodoApp.jsx'], function(require) {
  const TodoApp = require('TodoApp/client/components/TodoApp.jsx');
  console.log('TodoApp', !!TodoApp);
})

```

triggers:
```
W20160523-16:36:31.993(-4)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160523-16:36:31.994(-4)? (STDERR)                    throw(ex);
W20160523-16:36:31.994(-4)? (STDERR)                          ^
W20160523-16:36:32.010(-4)? (STDERR) Error: Cannot find module '/Users/me/kickstart-meteor-react-flowrouter/.meteor/local/build/programs/server/npm/node_modules/1.server.js'
W20160523-16:36:32.010(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160523-16:36:32.011(-4)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160523-16:36:32.011(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160523-16:36:32.011(-4)? (STDERR)     at require (module.js:380:17)
W20160523-16:36:32.011(-4)? (STDERR)     at Npm.require (/Users/me/kickstart-meteor-react-flowrouter/.meteor/local/build/programs/server/boot.js:182:18)
W20160523-16:36:32.011(-4)? (STDERR)     at Function.requireEnsure [as e] (webpack:/webpack/bootstrap 72e301b0d0483e2b8f24:43:1)
W20160523-16:36:32.012(-4)? (STDERR)     at Object.<anonymous> (webpack:///src/server.js:7:1)
W20160523-16:36:32.012(-4)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 72e301b0d0483e2b8f24:29:1)
W20160523-16:36:32.012(-4)? (STDERR)     at webpack:/webpack/bootstrap 72e301b0d0483e2b8f24:60:1
W20160523-16:36:32.012(-4)? (STDERR)     at webpack:/webpack/bootstrap 72e301b0d0483e2b8f24:60:1
```

(
However this works fine:
```javascript
// server.js
import 'TodoApp/server';

import TodoApp from 'TodoApp/client/components/TodoApp';
console.log('TodoApp', !!TodoApp);
// logs "TodoApp true"
```
)

Here is how to reproduce:
- clone the `kickstart-meteor-react-flowrouter` project
- change `server.js` to the above code snippet
- Alternatively, you can clone https://github.com/gsabran/kickstart-meteor-react-flowrouter/tree/server-side-require

Require seems to work fine on the client.

In case you're wondering why I'm trying to only load code when need on the server:
- I want to only load code bundles when needed on the client, so my client code would use require("...
- I want to do server side rendering, so my server has to be able to run client code.

Here is a version of `kickstart-meteor-react-flowrouter` with SSR I'd like to get to work (and that I'd be happy to share with the community): https://github.com/gsabran/kickstart-meteor-react-flowrouter/tree/srr

**Comment by eXon** [comment]
The good practice is usually to disable SSR on the server using `Meteor.isProduction`.

We should look if there is a way to support that so SSR is easier to deal with. Great idea!

**Comment by gsabran** [comment]
I see, nice. I got confused by the fact that SSR runs on the server with `Meteor.isClient===true`

**Comment by gsabran** [comment]
I'll probably submit a kickstart project with ssr + code splitting.

**Comment by gsabran** [comment]
Hum. But SSR is running on the server with `Meteor.isServer===true` and if disabled it will simply not work

**Comment by eXon** [comment]
Sorry I meant code splitting. Here is the idea:

```javascript
if (Meteor.isServer) {
  const test = require('./test');
  cb(null, test);
} else {
  require.ensure([], function(require) {
    const test = require('./test');
    cb(null, test);
  });
}
```

But it would be really cool to automatically do that on the server.

**Comment by gsabran** [comment]
Nice I'll look at it and try to bundle that nicely. I'll submit a kickstart project with SSR and code splitting when this is working. Another issue I've had with SSR is that:
```
import '../css/style.import.css';
```
will add a link to a stylesheet in the head on the client, but does nothing on the server, so the code returned by the server is missing the style and looks ugly.

To solve that, I'd like to have something like

```
import styleSheetSrc from '../css/style.import.css';
```

That'd do as before on the client, but would return a link to a stylesheet on the server I can add myself in the page been rendered in SSR.

The closest I got so far is with
```
import style from '!css!../css/style.import.css';
```
will have the content of the stylesheet under `style[0][1]`, but then nothing is added to the head in the client. So I can use that for SSR and add plain css text in the head (which is not great) but that then screw up the client rendering.
I honestly have no idea what is happening there and if you have some guidance that'd be great! 

Bottomline is that css is not added to the page rendered on the server and loads with delay when the client code runs. I'd like to solve that while keeping the client behavior.

**Comment by gsabran** [comment]
```
const style = Meteor.isClient ?
  require('../css/style.import.css') :
  require('!css!../css/style.import.css');
```
seems to do the trick.

**Comment by gsabran** [comment]
I've created a PR on https://github.com/thereactivestack/kickstart to add the repo with SSR and code splitting. Let me know what you think and how it could be improved

**Comment by eXon** [comment]
@gsabran I think it will help a lot people understand SSR with Webpack and Meteor. What you've done is great :)
