### ISSUE TITLE
Error with libsass binding

### ISSUE THREAD

**Issue by mvaivre** [thereactivestack/meteor-webpack#17]
Hi,

I have this issue where it seems that the build system is looking for a folder that doesn't exist (it seems to be looking for an older version of node-sass).

```ERROR in The `libsass` binding was not found in {Userparh}/.meteor/local/webpack-npm/node_modules/node-sass/vendor/darwin-x64-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.```

I have node version 4.2.1, and the folder inside node-sass/vendor is `darwin-x64-46`.

Obviously, `npm rebuild node-sass` doesn't work.

Any ideas?

Thanks in advance!

**Comment by ribbedcrown** [comment]
Check out this @eXon's [post on meteor forum](https://forums.meteor.com/t/webpack-compiler-inside-meteor-es6-modules-hot-reload-and-code-splitting/11264/142).

**Comment by eXon** [comment]
Let me know if you,re still having the problem.

**Comment by mvaivre** [comment]
Thanks a lot @ribbedcrown, it worked!

**Comment by samcorcos** [comment]
Yeah, I ran into this same issue. Is there any chance we could find a more elegant way to solve this? Unfortunately I don't know enough about the issue. 

Would MDG have to change something?

**Comment by eXon** [comment]
This was mainly due to the fact that your local version of Node is different than Meteor (0.10.40, pretty old). You should blame node-gyp / Node binary modules for that :(.

**Comment by ansonla3** [comment]
same got the same issue, any solutions? I already tried to run the fix-sass.sh script
ERROR in The `libsass` binding was not found in /.meteor/local/webpack-npm/node_modules/node-sass/vendor/darwin-x64-11/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by eXon** [comment]
@ansonla3 Use nvm to run NPM v0.10.40 and run npm rebuild node-sass in the project folder. It should fix the problem.

**Comment by ansonla3** [comment]
solved. many thanks.
