### ISSUE TITLE
release 1.3.3-beta.1 fails at method existsSync

### ISSUE THREAD

**Issue by menelike** [thereactivestack/meteor-webpack#170]
We need to use 1.3.3 (`meteor update --release 1.3.3-beta.1`) as we pray that build times may get faster.

Currently this fails because of:

```
While processing files with webpack:webpack (for target os.osx.x86_64):
  packages/webpack:webpack/plugin/WebpackCompiler.js:197:10: Object [object
  Object] has no method 'existsSync'
  at updateNpmPackages
  (packages/webpack:webpack/plugin/WebpackCompiler.js:197:10)
  at WebpackCompiler.processFilesForTarget
  (packages/webpack:webpack/plugin/WebpackCompiler.js:127:7)
```

I do not know if this is an API change or not. I'd be happy if `meteor-webpack` would release a `beta.1` as well to make this work again.

Thanks in advance.

**Comment by eXon** [comment]
This is probably not a big deal to fix. It looks like they have changed the filesystem API (that's weird).

**Comment by menelike** [comment]
It seems that `fs.exists` and `fs.existsSync` has become obsolete.
https://github.com/meteor/meteor/pull/7033/commits/355e850829ec00024f62024f05bf622015056bbc show how this can be done in future.

**Comment by eXon** [comment]
Node.js deprecated `fs.exists` for a long time I believe. I'll fix that.

**Comment by shijunti19** [comment]
I also need

**Comment by eXon** [comment]
Fixed in next released
