### ISSUE TITLE
Converting existing MeteorJS to Webpack app

### ISSUE THREAD

**Issue by scheung38** [thereactivestack/meteor-webpack#171]
I have an existing MeteorJS app, but trying to convert to Webpack app seems like a nightmare to me, as I can't seem to find any decent tutorials but very complicated starting from scratch new apps. Thanks

**Comment by laurentpayot** [comment]
Did you have a look at the [kickstart projects](https://github.com/thereactivestack/kickstart)? They are a good way to understand meteor-webpack logic.

**Comment by eXon** [comment]
There is no migration tutorial because their is not much to migrate outside setting up your entry files in your package.json.

**Comment by scheung38** [comment]
kickstart projects after cloned and npm install also dont work
