### ISSUE TITLE
How can we get sourcemaps?

### ISSUE THREAD

**Issue by rvetere** [thereactivestack/meteor-webpack#172]
Nice package! It just works after running `meteor add webpack:sass` and `meteor npm rebuild node-sass` 😄 

But as i see in the web-developer tools, it is not generating sourcemaps out-of-the-box.. Now i'm wondering how i can add it by webpack.json or if it needs a code-update of the package itself..?

Maybe it really needs a code-update? Because from my personal experience, you just need to add `?sourceMap` to the query-params of every involved loader (except the last style-loader)

**Comment by rvetere** [comment]
-> i've just created a new pull-request with a code change that would add the ability to activate style-source-maps in the webpack.json

https://github.com/thereactivestack/meteor-webpack/pull/179

**Comment by eXon** [comment]
Thanks for the help :)
