### ISSUE TITLE
Source maps with node_modules?

### ISSUE THREAD

**Issue by trusktr** [thereactivestack/meteor-webpack#173]
Some libraries on NPM have source maps, because the library may have been transpiled on `prepublish`. Is there a (perhaps planned) way to take advantage of these in `webpack:webpack`?

For example, package A's `main` file might be `dist/index.js`, and the corresponding source map might be `dist/index.js.map`.

Does `webpack:webpack` look at those? If not, maybe there can be a simple convention: for each `path/to/file.js` have `webpack:webpack` simply look for `path/to/file.js.map`, even if the file is in `node_modules`.

**Comment by eXon** [comment]
There is a source-map preLoader we can use. We should take a look at this.
