### ISSUE TITLE
Possible to add context regarding test mode for custom webpack conf?

### ISSUE THREAD

**Issue by ThisSentenceIsFalse** [thereactivestack/meteor-webpack#175]
Within my webpack.conf.js I overwrite the entry according to some of the context passed before evaluation (e.g. `isClient`, `isServer`). I'm also trying to set up unit and integration testing (somewhat within the Meteor 1.3. flow); however it appears from the source code that conf evaluation doesn't provide any `isTest`/`isFullAppTest` flags, which means I end up importing many useless chunks in these cases.

I have resorted for the moment to environment variables for filling the gap, yet I feel that getting them available along (maybe in the Meteor mock) would be a much better solution.

Thank you for the package again.

**Comment by eXon** [comment]
You can use `Meteor.isAppTest` and `Meteor.isTest`. They are supported.
