### ISSUE TITLE
Imports fail in meteor.startup.js

### ISSUE THREAD

**Issue by john-osullivan** [thereactivestack/meteor-webpack#176]
I'm getting `SyntaxError: Unexpected reserved word` when I try to import the `percolate:migrations` package in a meteor.startup.js file.  According to [this Meteor issue](https://github.com/meteor/meteor/issues/6146), the solution is to add `ecmascript` to the project.  However, this causes a new error because both `ecmascript` and `webpack:webpack` are trying to process `.js` and `.jsx` files.  I've tried putting the file in:

1. The server folder of one of my modules.
2. The webpack entry folder
3. The webpack `entry/server` folder

And I'm still getting the error.  Am I using the file improperly, or is it misbehaving?  Thank you!

**Comment by eXon** [comment]
They are obviously missing a dependency within the package. There is not much we can do about it outside reporting it to the package author.
