### ISSUE TITLE
css modules excludes, how?

### ISSUE THREAD

**Issue by rvetere** [thereactivestack/meteor-webpack#177]
It's awesome to have the css.modules=true option in webpack.json. But as it is - it doesn't make sense to load _all_ of the imported css's as a module - especially not for third-party modules which are not written in css-modules (regarding the generated html).

So normally, we would include two separate loader-definitions in our webpack.js - one which is doing all the "css-modules" imports, with an exclude for all third-party module paths (just exclude everything basically from "node_modules") and a second loader, doing all the imports the classic way (without css-modules), excluding all paths where the css-modules comes from.

How can achieve this with "meteor-webpack"?

**Comment by rvetere** [comment]
-> i've just created a new pull-request with a code change that would add the ability to define exclude-folders in the webpack.json

https://github.com/thereactivestack/meteor-webpack/pull/179

**Comment by eXon** [comment]
Thanks, I think it's a great idea.
