### ISSUE TITLE
Looking for index.js?

### ISSUE THREAD

**Issue by scheung38** [thereactivestack/meteor-webpack#178]
Before using meteor add webpack:webpack I had ecmascript in .meteor/packages running in Win 7 ok:

With webpack.config.js in both server and client

    module.exports = {
        devtool: 'eval-source-map',
        entry: "./entry",

        resolve: {
            extensions: ['', '.js', '.jsx', '.json']
        },
        module: {
            loaders: [
                {
                    test: /\.json$/,
                    loader: "json"
                },
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel',
                    query: {
                        presets: ['es2015', 'react']
                    }
                },
                {
                    test: /\.css$/,
                    loader: 'style!css?modules!postcss'
                },
                {
                    test: /\.jsx?$/,
                    loader: 'babel',
                    exclude: /node_modules/,
                    query: {
                        presets: ['es2015', 'react']
                    }

                }
            ]
        },
        devServer: {
            contentBase: "./public",
            colors: true,
            historyApiFallback: true,
            inline: true
        },
       postcss: [
            require('autoprefixer')
        ],

    };

But after 

meteor add webpack:webpack 
meteor add webpack:react
meteor add webpack:less
meteor add react-meteor-datat
meteor
npm install
meteor

as per instructions, now it is returning

Cannot find the entry point "index.js" for the web

**Comment by rvetere** [comment]
Did you add your entry-points for meteor-webpack in your package.json like this?

```
"main": "src/server.js",
"browser": "src/client.js",
```

It's un-common to put the entry-points for a webpack build in the package.json, so i'm pretty sure this is the only thing missing for your setup.

**Comment by eXon** [comment]
I'm not sure why you want to use custom loaders for stuff you can easily do by just adding packages (look at the doc).

For the error, it is because you don't specify your entry point in package.json.
