### ISSUE TITLE
Source maps for server code

### ISSUE THREAD

**Issue by jbbr** [thereactivestack/meteor-webpack#18]
It would be great to have source maps also for the server code.

Currently all stacktraces point to "server.js" with wrong line numbers.

jedwards got it working with [source-map-support](https://www.npmjs.com/package/source-map-support) - Commit https://github.com/jedwards1211/meteor-webpack-react/commit/958be22582b584bb7fc152f213f8611fe4a11441

**Comment by eXon** [comment]
The source map is sent to Meteor. But it doesn't seem to work well. I'll have to take a look why.

**Comment by jbbr** [comment]
ok thanks. I also thought that it indeed did worked on the past. But I just tried it with current kickstart-simple master and my own project and got errors with non helpful filenames/line numbers when intentionally adding undefined calls etc.

**Comment by jbbr** [comment]
BTW: Downgrading kickstart-simple to e.g b4f734fddd4cb63870957117bc411836cb12cc42
brings source maps back (Not perfect but at least correct file names and line numbers with webpack:/// urls).
After a "meteor" update source maps are broken again. Seems to be caused by some changes in meteor-webpack. I can try to find the commit which broke this.

**Comment by eXon** [comment]
It is probably because of the devtool config. If you set `devtool: 'source-map'` in your webpack.conf.js file, is it fixing it?

**Comment by jbbr** [comment]
You are right, thanks. Adding this to server webpack config fixes source maps for me.
