### ISSUE TITLE
webpack:blaze implementation?

### ISSUE THREAD

**Issue by citizenkevin** [thereactivestack/meteor-webpack#182]
Hey, Benoit. What's the timeline for webpack:blaze? 

The team might be interested in getting this going so we can use it for a blaze project. Any initial tips/things we need to know for contributing if it's still off the radar for you?

**Comment by eXon** [comment]
Is there any solid webpack loader for Blaze ATM?

**Comment by citizenkevin** [comment]
Not that I'm aware of. Just did a quick forum search, and all that came up is some links from you. 
I take it this is the bottleneck?

**Comment by eXon** [comment]
No need to keep this open. I think Blaze is dying TBH.

**Comment by nicooprat** [comment]
I think a lot of people are still using Blaze, but it's not as hyped as React and others these days, so one can feel it's dying. I'd really like to see the Blaze implementation happen! Especially for features like:

* code splitting
* hot module replacement
* single file templates (not sure it's possible?)

Found this https://github.com/xamfoo/spacebars-loader that might be a starting point for Blaze templates...?

**Comment by linegel** [comment]
@eXon In fact blaze not dead 
it can be understand after see repo https://github.com/meteor/blaze/
