### ISSUE TITLE
connecting on Ipad localhost issue

### ISSUE THREAD

**Issue by deadorafk** [thereactivestack/meteor-webpack#184]
When connecting via Ipad to my meteor hosted on my macbook hmr keeps pointing to http://localhost
Also images loaded with require will point to localhost

I enter something like the following in my webpack.json

```
"devServer": {
    "host": "192.168.something.something"
}
```

Any idea on what I need to change to be able to run meteor from my macbook with webpack and connect to it with my ipad?

I used one of your kickstart examples (which are awesome btw)

**Comment by teebszet** [comment]
I also tried setting 

"devServer": {
    "host": "0.0.0.0"
}

but according to netstat, the server still binds to 127.0.0.1

**Comment by eXon** [comment]
0.0.0.0 is great if you want to listen to any ip address, but will not help to resolve the local ip address. You have to set manually your own ip address if you want to use it remotely.

**Comment by teebszet** [comment]
> You have to set manually your own ip address if you want to use it remotely.

Ok, but as I understand it, this is a feature of webpack: https://github.com/webpack/webpack-dev-server/pull/263

**Comment by teebszet** [comment]
@eXon a possible solution? : https://github.com/davezuko/react-redux-starter-kit/commit/dd1ac21a8e4eb7562d3e1a3d39437aff29674162
