### ISSUE TITLE
Use custom webpack config?

### ISSUE THREAD

**Issue by gsabran** [thereactivestack/meteor-webpack#186]
Per the doc, it's not clear it is possible to customize the webpack config outside of what the `webpack.json` allows. I think that `webpack.config.js` is ignored but `webpack.conf.js` works. However that seems to break what meteor-webpack is doing.
I'd like to be able to do things like [removing warning in react](http://dev.topheman.com/make-your-react-production-minified-version-with-webpack/) but I'm not sure how

**Comment by eXon** [comment]
Yea thanks for noticing that. I've added webpack.config.js to the list of files the plugin read.

The warnings are also removed by default now in production.
