### ISSUE TITLE
http://localhost:3500/assets/web.js 404

### ISSUE THREAD

**Issue by wangyueming** [thereactivestack/meteor-webpack#188]
There is an error as title. I don't know why? I work on mac OS X Yosemite. The meteor version is 1.3.2.4.

**Comment by santiagopuentep** [comment]
Content Security Policy maybe?

**Comment by TamarAmit** [comment]
Hey, 
Try to change the host of the webpack.json file.
Under devServer to your local host, if you are working through a remote env it could be an ip.

**Comment by eXon** [comment]
If you're not working on localhost, you have to set the correct IP using devServer option.
