### ISSUE TITLE
Can't use this project because it forces relative paths

### ISSUE THREAD

**Issue by radixhound** [thereactivestack/meteor-webpack#191]
I am trying to swap an existing project to use this and am blocked because I can't figure out how to configure imports to use absolute paths. It seems like webpack supports all kinds of configuration to make this easy but there is nothing in the documentation for this project to explain how to use custom configuration for web pack. The only thing listed is `webpack.json` in the root of the project which limits the number of configs that can be used.

1. How can we set `resolve.alias`?
2. How can we set `resolve.root` to the root of the project?
...etc.

There is an issue here #5 but it just says 'fixed' and doesn't say how it was fixed or how to use the same pattern for a project. If someone can explain how to allow files to use absolute paths, that would be FANTASTIC.

Some context:

1. I have package.json looking like this:
```json
{
  "main": "server/main.js",
  "browser": "client/main.js",
}
```
2. `server/main.js` looks like this:
```javascript
import '../imports/starup/server/main.js'
```
* note the relative path is required
3. `startup/server/main.js` looks like this
```javascript
import '/imports/api/collections'
```
here things start to get hectic because we have 90+ files that are using import with an absolute path and updating all of those to be relative (e.g. `'../../../../imports/...'`) is insanity.

**Comment by eXon** [comment]
You can add to your .babelrc file the babel plugin `babel-root-slash-import` or you can simply set the "root" variable to any folder and then you can require or import from the root anywhere.

**Comment by radixhound** [comment]
Thanks for the tip. I was trying to set the root but it wasn't working though. The folder structure for our project is unlike the sample apps though. Something like this:

```
- client
  - main.js
- imports
- server
  - main.js
package.json
webpack.json
```

webpack.json looked like this
```
{
  "root": "/"
}
```

I tried a few variations but no luck. I suppose if everything was in a `src` folder then I could have set `"root" : "src"` but alas! I want to avoid reorganizing the whole project... Maybe the babel thing will work out.

**Comment by eXon** [comment]
If you're using root, you don't need the forward slash at the beginning. You can just do
```js
import main from 'server/main';
```

**Comment by yched** [comment]
One big drawback of using root paths is that, since they rely on webpack or babel confg, I couldn't get WebStorm to understand them (for e.g. autocompletion or ctrl-click navigation).

Would be happy to know if there are workarounds I missed :-)

**Comment by eXon** [comment]
Yea I know I have the same problem with Atom. Also have the same problem with Webpack alias.

**Comment by funkybunky** [comment]
After implementing the mentioned solution (adding `babel-root-slash-import` and `"root": "/"` to webpack.json and then stripping away the first slash of the imported absolute paths), eslint couldn't resolve the paths anymore. I fixed this issue by adding [eslint-import-resolver-meteor](https://www.npmjs.com/package/eslint-import-resolver-meteor) to the project and adding this to `.eslintrc`:
```
  "settings": {
    "import/resolver": {
      "meteor": {
        "extensions": [".js", ".jsx", ".es6" ],
        "paths": [ "/usr/local/share/global_modules" ],
        "moduleDirectory": [ "node_modules", "/" ]
        }
      }
    }
```
Just in case somebody runs into the same issue I thought it would be a good idea to reference it here.

**Comment by markoshust** [comment]
@funkybunky thanks very much. this one is simpler if you want to want to include just the imports directory:
```

  "settings": {
    "import/resolver": {
      "meteor": {
        "moduleDirectory": [ "node_modules", "imports" ]
      }
    }
  }
```
