### ISSUE TITLE
Speed Up Build with Multicore

### ISSUE THREAD

**Issue by Falieson** [thereactivestack/meteor-webpack#193]
Since installing webpack my build times are much longer when working on API changes. I also notice that every time meteor builds it only uses 1 of my cpu cores. I've done a little research and come across this package https://www.npmjs.com/package/parallel-transpile but I'm not sure how to integrate into my app. I'm using 
meteor add webpack:webpack and webpack:react.

If someone has done this already I'd appreciate your aid, thanks!

[Also asked on the Forums](https://forums.meteor.com/t/use-multi-core-to-speed-up-building-os-osx-x86-webpack/24764)

**Comment by gsabran** [comment]
+1!

**Comment by Falieson** [comment]
Also asked on Stack: http://stackoverflow.com/questions/37778227/use-multi-core-to-speed-up-building-os-osx-x86-webpack

**Comment by eXon** [comment]
I have no plan to implement this but I'll gladly review a PR if you would like to contribute.

**Comment by Falieson** [comment]
Agreed. Since Meteor 1.4 rebuilding the server side of the application doesn't take very long at all. It's no longer a priority for me either.
