### ISSUE TITLE
Alias modules in webpack.json

### ISSUE THREAD

**Issue by smothers** [thereactivestack/meteor-webpack#194]
Is it possible to add an alias? Ideally in webpack.json.

I'm getting this error:

`
modules.js?hash=f9b45ef…:33607 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
`

And I'd like to do something like this to alias react:

```js
module.exports = {
  ...
  resolve: {
    alias: {
      'react': path.join(__dirname, 'node_modules', 'react')
    },
    extensions: ['', '.js']
  },
  ...
);
```

Is this currently supported in webpack.json or webpack.conf.js?

**Comment by coniel** [comment]
Did you figure out how to do it? I'm having the same issue.

**Comment by eXon** [comment]
Support for alias in the webpack.json config file has been added.
