### ISSUE TITLE
webpack:blaze still coming?

### ISSUE THREAD

**Issue by tcastelli** [thereactivestack/meteor-webpack#197]
Would like to know if that is still planned, would love to try that out! :)

**Comment by eXon** [comment]
No. There is no decent webpack loader and it's dying.

**Comment by talha-asad** [comment]
Blaze isn't dying, MDG is working to make it community driven. Let me know if you guys have made any progress in that direction so people like me can take up the lead on it. Would love to have a blaze working with Webpack and Meteor.

**Comment by eXon** [comment]
Their is no plan to add a loader for now. Anyone could make the package if a good Webpack loader exists.
