### ISSUE TITLE
react-hot-loader

### ISSUE THREAD

**Issue by sankaku-io** [thereactivestack/meteor-webpack#199]
Do you have any plans to use react-hot-loader? (package webpack:react)

https://github.com/gaearon/react-hot-loader

**Comment by eXon** [comment]
Yup. Just haven't got the time to do it yet.

**Comment by rvetere** [comment]
i will do it! i just have one big issue in my understanding :-/ i've tried it already manually to kick out "react-transform" what is basically the reason why HMR is not working right now with "stateless-function-components" (that's why i want to push the HMR in this stack to the next level)

Now i've found cool material - as "react-transform" is already marked completely as _deprecated_ in the official repo:

* [Big Update coming to react-hot-loader](https://github.com/gaearon/react-hot-boilerplate/pull/61)
* [Good starting point for it (no docs yet)](https://github.com/gaearon/redux-devtools/commit/64f58b7010a1b2a71ad16716eb37ac1031f93915)

I will try now to basically implement those changes from the linked example (second link) and just hope that it will be more successful than my manual attempt ^^

**Comment by srobinson** [comment]
This is a good reference

https://github.com/ctrlplusb/react-universally

**Comment by rvetere** [comment]
Just as an update.. i was working yesterday way too long on this topic, aaaaaaaand... without any luck -.-

I got everything included exactly like described in the pull-request / or in the awesome "react-universally"...

react-hot-loader is truly awesome! It comes now with extremely helpful error messages in your console, guiding you trough all pitfalls.

I got to the point where all errors are gone and it seems to work _perfectly_ - at least what the console tells.

I can now change something in a component - i see webpack building - then i see in the browser console how HMR kicks in, picks up the changed module and updates it - saying in the end "App is up to date" -> this is exactly the point you have to reach so it _will_ work (no horror anymore with "don't know how to update themselfs")....

But - the point is - the UI just don't update at all! HMR is just telling that everything is fine, but NOTHING is fine at all!

So i guess i'm truly fucked up now as now errors are left, no entries are found about such a behavior in any troubleshooting doc and... i'm slowly loosing any motivation to fiddling around in that topic anymore... sorry about that..

Well i will make a pull-request i think on the "kickstart-meteor-react-router" project just to show off the changes to all you guys i made and - to show off how it updates, and don't update (little bit like schrödingers cat right :P)

**Comment by rvetere** [comment]
Ok, took me longer as i thought (was too busy).. but here is my commit with all the changes:

https://github.com/rvetere/kickstart-meteor-react-router/commit/1c038db714e7365f1ab15a492513991184df5bd9

it's a fork of the "kickstart-meteor-react-router" project where i already included a basic redux-routing before, you can check it out here: https://github.com/rvetere/kickstart-meteor-react-router

the status with the hot-loader is exactly as i described before, you can check this out in the branch "hot-loader"

be aware - i had to include the packages "webpack:react" and "webpack:webpack" locally in the project, and then changed them a bit accordingly to the needs of react-hot-loader.

as i saw now, my fork where i got those basic plugins from was not up-to-date - when we finally could fix the hot-loader and proceed with the changes i would of course fix this detail ;)

**Comment by focused** [comment]
I use livescript/coffeescript and 'webpack:react' with 'react-transform' does not work at all for me (neither hot nor live reload), webpack meteor package have serious limitations :(
Maybe it will work with 'react-hot-loader'...

**Comment by rvetere** [comment]
it is pretty easy to modify the "limitations" of webpack meteor package... just checkout the repository here, pick a plugin from the folder "packages", and copy-paste it to a local "packages" folder in your project.

after that, you can modify the "webpack.config.js" inside of the plugin and extend it in all likings. so if you can find out this way what is missing/bugging you that livescript/coffescript is not working, we would be happy about a PR here 👍

**Comment by laurentpayot** [comment]
Thanks @rvetere for the how-to. I didn't know it was that easy. I could fix a bug with livescript-loader, created PR https://github.com/thereactivestack/meteor-webpack/pull/252 .

@focused maybe my little bugfix will help you. webpack:livescript is working great for me now, I also use it in my Vue single file components.

**Comment by eXon** [comment]
I'm not going to migrate for now but if anyone think it would definitively improve, you can make a PR (I don't have time for this :()
