### ISSUE TITLE
Can't install Radium

### ISSUE THREAD

**Issue by imkost** [thereactivestack/meteor-webpack#2]
I have an issue on Mac OS X:

1) `git clone https://github.com/thereactivestack/kickstart-simple kickstart`
2) `cd kickstart`
2) Add `"radium": "0.14.1"` to `packages.json`
3) `meteor`
4) Then I have infinite "building npm-container package" message and CPU 95% load

**Comment by imkost** [comment]
Well... as it turned out, if I wait for 5 minutes, Radium is successfully installed. It is not only Radium takes so much time, but any package which I add to `packages.json`.

**Comment by eXon** [comment]
I'll have to investigate more on that. It takes a lot more time than it should be. Especially in production mode. I bought a Macbook Pro last week so I guess it should be super-fast and NPM packages are taking a while to install.

Do you have the same problem when using meteorhacks:npm without Webpack?

**Comment by imkost** [comment]
I started pure meteor application, added `meteorhacks:npm` and the same `packages.json` file I've used with kickstart. Same problem.

So the problem is related to `meteorhacks:npm` and not to kickstart. Close the issue.

**Comment by eXon** [comment]
Good to know but worried I can't fix it :( It looks like the node_modules has a massive amount of files. Do you think the Meteor NPM is acting weird?

**Comment by rclai** [comment]
I also experienced extreme slowness in `meteorhacks:npm` "building" the `npm-container`. @eXon are you going to build a `meteorhacks:npm` replacement?

**Comment by eXon** [comment]
It's not a replacement. They both have a reason to exist.

webpack.packages.json -> it will be NPM modules you can bundle with your own javascript
packages.json: NPM package you want to use on the server with Node.js
