### ISSUE TITLE
Multiple JS outputs

### ISSUE THREAD

**Issue by gunn** [thereactivestack/meteor-webpack#202]
Is there a good way to output multiple top-level javascript files. E.g. client.js and admin.js ?

Since they're separate apps (but sharing some logic) I don't think code-splitting would be an ideal solution.

**Comment by eXon** [comment]
This is not supported ATM. It would be weird because it is tied to Meteor build system. How would you do that?

**Comment by gunn** [comment]
@eXon Well on the webpack side with multiple entry points. I don't know how the tie-in with the meteor build system works though. What are we missing if we just add an `import { Meteor } from 'meteor/meteor'` to a top-level file?

**Comment by eXon** [comment]
Their is no plan to support this ATM.
