### ISSUE TITLE
Webpack + SSR question

### ISSUE THREAD

**Issue by SachaG** [thereactivestack/meteor-webpack#205]
The guide mentions that:

> anything you might want to hot reload has to be within a client folder

How does that work with SSR then? Maybe a small note about this could be added to the guide? (sorry if you address that later, I'm still on day 2 ;)

**Comment by gsabran** [comment]
I'm not sure about hot reload with SSR (I gave SSR + webpack a try [here](https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit))
The thing is that server rebuild is slow (very slow?) so if your server is watching client code as well (as you'd do for SSR), it's gonna rebuild every time.
I don't know if this slow rebuild comes from Meteor or webpack. Maybe @eXon can tell us more about that.
What I ended up doing is enable SSR in production only, where I don't care about hot reload.
What's a use case where you want hot reload for SSR code?

**Comment by SachaG** [comment]
Well I want to hot-reload my React components, which are also SSR'd.

**Comment by gsabran** [comment]
Ah sure. Well I disabled SSR in development to make sure that'd work fine. Not sure about how to get this to work

**Comment by SachaG** [comment]
How do you disable SSR in development only?

**Comment by gsabran** [comment]
in https://github.com/gsabran/kickstart-meteor-react-flowrouter-SSR-codeSplit/blob/master/src/server/index.js#L30-L33 I only load client routes from the server if a condition is met:
```js
// server/index.js
if (process.env.NODE_ENV === 'production') {
  const { setUpRoutes } = require('../client/routes.jsx');
  setUpRoutes();
}
```

**Comment by eXon** [comment]
I think the answer has been clearly answered :)
