### ISSUE TITLE
Silence build chunk info by passing "stats": "errors-only"

### ISSUE THREAD

**Issue by jdanilov** [thereactivestack/meteor-webpack#206]
I have the same issue as described here: https://github.com/webpack/webpack/issues/1191, however specifying stats: errors-only in webpack.json has no effect:

```
{
  "root": "sources",
  "devServer": {
    "host": "localhost",
    "stats": "errors-only"
  },
  "externals": {
    "React": "react"
  }
}
```

Can support for stats be added to the webpack.json?

**Comment by jdanilov** [comment]
I also tried to use webpack.conf.js file but it seems most of the fields are being skipped. It'd be useful if the entire webpack.conf.js is to be parsed by webpack:webpack as-is but then enhanced with additional rules.

**Comment by eXon** [comment]
This should be fixed.
