### ISSUE TITLE
File loader doesn't work properly

### ISSUE THREAD

**Issue by vsheyanov** [thereactivestack/meteor-webpack#208]
I've added AmCharts to the React app.
AmCharts references images using relative path like

`<image xlink:href="img/lens.svg"></image>`

I'm trying to copy all required files from `node_modules/amcharts3/amcharts/images/` to an output folder using this code:
`const imagesContext = require.context('!!file?name=app/img/[name].[ext]!amcharts3/amcharts/images');`
`imagesContext.keys().forEach(imagesContext);`

Output from the console shows this:
> [1227] ./~/file-loader?name=app/img/[name].[ext]!./~/amcharts3/amcharts/images/lens.png 62 bytes {0} [optional] [built]
> [1228] ./~/file-loader?name=app/img/[name].[ext]!./~/amcharts3/amcharts/images/lens.svg 62 bytes {0} [optional] [built]
 
As you can see all files have the same wrong filesize about 60-80 bytes (original files are bigger).

Looks like file-loader doesn't work properly.

Similar issue (but without meteor/react) https://github.com/webpack/webpack/issues/2354

**Comment by eXon** [comment]
This is not Meteor related and I don't think we can do anything about it. Looks like the Webpack issue  has been fixed.
