### ISSUE TITLE
I'm having an issue when using this with material-ui

### ISSUE THREAD

**Issue by gabrielhpugliese** [thereactivestack/meteor-webpack#21]
In order to some of components from React material-ui to work, we need to run a simple snippet:
```
var injectTapEventPlugin = require("react-tap-event-plugin");
injectTapEventPlugin();
```
This need to run before we render anything as we can see here: https://github.com/callemall/material-ui/issues/1011#issuecomment-117841529

But I'm adding that code to `entry/client/entry.js` and I think it's not running before the first render. Also tried with `Meteor.startup()` block but with no luck.

Do you have any recommendation here?

**Comment by gabrielhpugliese** [comment]
BTW I'm using the hugeapp skeleton

**Comment by gabrielhpugliese** [comment]
Newest try:
I've cloned this repo to `packages/` and remove this line: https://github.com/thereactivestack/meteor-webpack/blob/05f3104f48d81614a5c4c3653e0c1490aca55239/plugin/WebpackCompiler.js#L109
Then I `rm -r node_modules/react`.

Now when I try to require the `react-tap-event-plugin` it raises error due to its dependencies from the react module from npm (that probably Meteor's react doesn 't have):

```
ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/injectTapEventPlugin.js 2:10-45

ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-56

ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginUtils' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-60

ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPropagators' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-60

ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/SyntheticUIEvent' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-60

ERROR in ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in /home/vagrant/Workspace/voce-noel-front/.meteor/local/webpack-npm/node_modules/react-tap-event-plugin/src
 @ ./.meteor/local/webpack-npm/~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58
```

And if I change Meteor's React package with the npm's I lose the mixin.

**Comment by gabrielhpugliese** [comment]
Ok, I confirm that's the issue that I've pointed above. It's injecting the `tap-event` on the react from npm, not from Meteor's. I just removed all React packages from meteor package system, created a `meteor-data-mixin` for my project and it worked!
Somehow I've lost the HRM and I have to restart Meteor every change I make :( :( :(

**Comment by eXon** [comment]
If you wish to execute anything before startup, put it inside a `meteor.startup.js` (anywhere).

**Comment by gabrielhpugliese** [comment]
That's not the issue. Just ignore the first message.
The issue is having 2 reacts at the same time.
I really want to show you this, so you have spare time to make a hangout?

**Comment by eXon** [comment]
Do you have a project I can see your problem with 2 react?

**Comment by gabrielhpugliese** [comment]
I will a brand new because I'm using the other at work :)

**Comment by gabrielhpugliese** [comment]
https://github.com/gabrielhpugliese/meteor-webpack-two-react-issue

The dropdown is not opening. How it should work: http://material-ui.com/#/components/dropdown-menu
The requirements for `DropDownMenu` to work: You gotta initialize [react-tap-event-plugin](http://material-ui.com/#/get-started/installation). It kinda monkey-patch/inject that event.
My bet on why it's not working: Since we have npm's package and Meteor's package, it's patching the npm one. But the entire application is using Meteor's one. But I'm not sure.
Why do I think that: I've removed Meteor's one on my other project and it worked. (I've copied [MeteorReactData](https://github.com/meteor/react-packages/blob/devel/packages/react-meteor-data/meteor-data-mixin.jsx) and put on project then I import when needed - had to do that because Meteor's react package is a dependency)

**Comment by genyded** [comment]
[Here](https://github.com/hartmamt/react-with-tap-events) summarizes the issue (we're using an external react) and has a patch - but I am not very familiar with webpack yet and not sure how to integrate it. There is also a link to the tapeventplugin issue related to this, but the only real way to fix.patch it is in the webpack stuff.

I am facing this too so hopefully someone can help and either say explicitly what to do in using reactivestack or better yet - just add it (optionally if possible).

**Comment by eXon** [comment]
I'll take a closer look into this when I have time and see what we can do. I'm sure there is a way to fix that.

**Comment by coniel** [comment]
I was having the same issue, so I created a package (```coniel:react-tap-event-plugin```) that's basically a wrapper for ```react-tap-event-plugin``` and exports ```injectTapEventPlugin```. To use it, just add the package and call ```injectTapEventPlugin()``` where you normally would.

It would be nice not to need a package though.

**Comment by gabrielhpugliese** [comment]
I wish we didn't need the Meteor's React at all, because they need to update it every time Facebook releases a version. Don't know if we can with the ReactRouterSSR though.

**Comment by genyded** [comment]
@coniel - BRILLIANT!!! I was so focused on trying to get it integrated the "normal" way it did not even occur to me to check Atmosphere (or just create my own as a Meteor package). Yours allows the material-ui components to function properly - thanks for that!

Let's just hope between all the change in Meteor, React, Material UI, and the tap event plug-in this all keeps working - there has been issue after issue with this stuff even without Meteor in the mix. Thanks again for doing this and posting it though - if things do break - I'm sure someone else will be the culprit ;-)

@eXon (Benoit) - This means for now - we can continue to use the ReactiveStack stuff (which we LOVE!!!!!!). I just wanted to THANK YOU (and the team if there is one) for putting together some great, solid stuff and for being SO responsive!!!! I'll sure help out with anything you may need where and when I can! Not we all go back to trying to hit our moving targets ;-)

Dale

**Comment by coniel** [comment]
Yeah, same here. I was planning not use Meteor's React until I noticed that it's required by ReactRouterSSR. It took them almost a month to catch up when React 0.14 was launched (I understand why, it was a big change, but it's still a pain to wait).

@eXon, would it be possible to make a version of ReactRouterSSR that doesn't rely on the Meteor React package? Would it be as simple as swapping out ```api.use('react-runtime')``` for ```Npm.depends([react packages...])``` and setting it up with browserify (in both your react-router and react-router-ssr packages)? If that's the case, I could fork the packages and maintain the non Meteor React versions.

@genyded glad I could help someone else out!

**Comment by eXon** [comment]
@coniel I'll look at how i can do that. I think this is a great idea!

**Comment by rkstar** [comment]
@gabrielhpugliese did removing meteor's react get rid of the "duplicate react" errors?

**Comment by gabrielhpugliese** [comment]
@rkstar Yes. I needed to get ReactMeteorData mixin from the official repo and add to a file in my project AND stopped using ReactRouterSSR for server-side rendering

**Comment by eXon** [comment]
I don't think any action is needed here so I'm closing this.

**Comment by samrispaud** [comment]
@gabrielhpugliese we're using Facebook's react and material-ui and I am getting these same errors. Was there a fix you came up with for this? Does it occur with certain version of these packages and get fixed when upgrading or downgrading?

```
ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-37

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventConstants' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-56

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginUtils' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPropagators' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/SyntheticUIEvent' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-60

ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/ViewportMetrics' in /Users/sam/avhana_projects/athene/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58
```

**Comment by gabrielhpugliese** [comment]
Hi,

It's been a long time since this issue. I tried to stick with only one
version of react, probably the one from webpack. It was a bit hard to
remove the other one. Maybe someone already figured out how to fix in
another way.

**Comment by samrispaud** [comment]
@gabrielhpugliese thanks for your help. using react v15 and material ui v15 and still running into the issue but will continue to investigate

**Comment by joshunger** [comment]
@samrispaud we're seeing the same issue in our builds this morning... do you know what changed?

**Comment by Marchys** [comment]
Not using Meteor-webpack but I have the same problem with new react version:
react: 15.4.0 // crash
react-dom: 15.4.0 // crash
react: 15.3.2 // works
react-dom: 15.3.2 // works

**Comment by vinzscam** [comment]
@samrispaud it seems that `react-tap-event-plugin` hasn't been updated to the last React. It should work if you use react v15.3.2.

**Comment by joshunger** [comment]
https://github.com/zilverline/react-tap-event-plugin/issues/85

**Comment by samrispaud** [comment]
@joshunger looks like that is the issue. @vinzscam locking my version of react at v15.3.2 allowed webpack to build successfully and remove those errors. but now anything in our app that relies on material-ui and react-tap-event-plugin is not clickable (ie dropdowns, etc) 😞

**Comment by cdleon** [comment]
Having the same issue.

Using react and material-ui, no meteor.

crashes with:
"react":  "^15.3.2" (using 15.4.0)
"react-dom": " ^15.3.2" (using 15.4.0)

works with:
"react": "15.3.2 "
"react-dom": "15.3.2"

**Comment by samrispaud** [comment]
@cdleon the issue was related to an update with react breaking react-tap-event-plugin. the PR was merged in so as long as you use ```"react-tap-event-plugin": "git+https://github.com/zilverline/react-tap-event-plugin.git#master"``` you should be good to go. Things are working for me and I'm using the following set up 
```
"react": "^15.4.0",
"react-dom": "^15.4.0",
"material-ui": "^0.15.4",
"react-tap-event-plugin": "git+https://github.com/zilverline/react-tap-event-plugin.git#master",
```

**Comment by cdleon** [comment]
@samrispaud yeap that fixed it, thanks!

my final setup following your suggestion

```
    "material-ui": "^0.16.2",
    "react": "^15.4.0",
    "react-dom": "^15.4.0",
    "react-tap-event-plugin": "git+https://github.com/zilverline/react-tap-event-plugin.git#master",
```
