### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by santiagopuentep** [thereactivestack/meteor-webpack#210]
I´m getting an Uncaught ReferenceError: React is not defined in the 
    `ReactDOM.render(<HelloApp />, document.getElementById("react-app"));`
line of the day 2 example, client.jsx file.

There´s no React in the code, it seems to be the <HelloApp /> part, not detecting jsx maybe?

Using Meteor 1.3.4 on Windows.

**Comment by gsabran** [comment]
What if you add `import React from 'react';` at the beginning of the file?

**Comment by santiagopuentep** [comment]
Yes but it´s the same, there´s no React being used, only ReactDOM. I don´t see why this could be happening. That´s the only line being used. If I comment that line there no error.

**Comment by gsabran** [comment]
I think you need to have React in the scope to be able to use the JSX syntax. I agree it's not intuitive. Does you problem get solved if you import react?

**Comment by santiagopuentep** [comment]
I followed day 2 tutorial again and added the React import and it worked. The hot reloading is amazing!

It was simply that missing import in the tutorial file.

Thanks for the help!

**Comment by gsabran** [comment]
Nice! Well you can do a PR for the tutorial I guess :)

**Comment by santiagopuentep** [comment]
Sorry, PR?

**Comment by gsabran** [comment]
Pull Request :)
Like fork the repository, make the changes needed and submit a PR, which is like "Hey here's some improvement I've done. Do you want to include them in your repo"
It's quite easy to do with the github interface.

**Comment by santiagopuentep** [comment]
Tried but it´s failing to clone the repo. Command line, sourcetree and github desktop.

Fails here in windows. It seems to be the `:`.
fatal: cannot create directory at 'packages/webpack/.npm/plugin/webpack:webpack': Invalid argument

**Comment by eXon** [comment]
Looks like you problem is fixed :)
