### ISSUE TITLE
cannot resolve module 'sass'

### ISSUE THREAD

**Issue by copleykj** [thereactivestack/meteor-webpack#220]
Added webpack:sass to my project, created a .scss file in the same folder as the component that imports it, and imported it as `import './component.scss'`. When project builds I get an error stating that the sass module can't be resolved. Any help would be greatly appreciated.

**Comment by pyrostrex** [comment]
@copleykj, I solved it with `meteor npm install --save node-sass sass-loader`

**Comment by copleykj** [comment]
@pyrostrex thanks so much!
