### ISSUE TITLE
Cannot find module './_baseClone'

### ISSUE THREAD

**Issue by yonidej** [thereactivestack/meteor-webpack#222]
I get this error every time I try to run my application. Any ideas on how to fix this?

**Comment by copleykj** [comment]
I had this same issue. Solved it by deleting the node_modules dir and ran `npm install` with an updated version of npm

**Comment by eXon** [comment]
Have you tried removing node_modules folder and run `meteor npm install`?

**Comment by yonidej** [comment]
Thank you, it works!
