### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by niallobrien** [thereactivestack/meteor-webpack#24]
I'm getting the above error in my console, on `<!DOCTYPE html>` and the rest of the html which is in `build.js`.

**Comment by eXon** [comment]
Where are you adding your code? Is it in a JSX file? I need more infos to help you.

**Comment by niallobrien** [comment]
Sure, it's in a .vue file here: https://github.com/niallobrien/vue-webpack-meteor-example/blob/master/client/app/app.vue

**Comment by eXon** [comment]
I'll have to run your project to see your problem, I'm not familiar with vue. It's awesome you're trying to make it work with webpack! :)

**Comment by niallobrien** [comment]
Thanks, if I can get this working next on the list would be VueLayout for FlowRouter. :)

**Comment by eXon** [comment]
Remove in `index.html`:

```<script src="/build.js"></script>```

Meteor/Webpack build system is taking care of doing that. I've tried your project and it seems to work.

**Comment by niallobrien** [comment]
Ok thanks, that resolved that error, but the app still fails to mount to `#app` - a simple todo app example should appear.

**Comment by iamsaksham** [comment]
Now did it work @niallobrien ?? I'm getting a somewhat same issue
