### ISSUE TITLE
webpack:blaze (coming soon)

### ISSUE THREAD

**Issue by Maxhodges** [thereactivestack/meteor-webpack#247]
I looks like it's been a couple months since the last commit on this repo. Is it safe to say a Blaze <> Webpack solution is no longer coming soon?

**Comment by rjakobsson** [comment]
I'm also interested in if it's coming or not. If not I'll rewrap all of our stuff in some reacty thing.

**Comment by eXon** [comment]
Anyone could do the Blaze Meteor package. Their is no support planned ATM.
