### ISSUE TITLE
Error in webpack compiler

### ISSUE THREAD

**Issue by vjau** [thereactivestack/meteor-webpack#25]
I get the following error when running my project :

```
While processing files with webpack:webpack (for target web.browser):
   native: Unexpected token }
   at Object.parse (native)
   at plugin/WebpackCompiler.js:115:48
   at Array.forEach (native)
   at runNpmInstall (plugin/WebpackCompiler.js:114:9)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:68:5)
```

Where could it come from ?

Thank you.

**Comment by vjau** [comment]
Ok, with some debugging i got it, there was a trailing comma in my webpack.packages.json.
Perhaps there could be some warning about improper formatting ? But perhaps it's more a webpack issue ?

**Comment by eXon** [comment]
I've added a check in case your webpack.packages.json has an error.

**Comment by vjau** [comment]
Thank you.
