### ISSUE TITLE
/imports folder is not recognised

### ISSUE THREAD

**Issue by Deadarius** [thereactivestack/meteor-webpack#254]
Following meteor 1.3 update we started actively using /imports folder. This package's webpack configuration doesn't seem to have a support for it neither does it expose alias configuration.

**Comment by eXon** [comment]
When using Webpack, you don't really need to use /imports folder. Your files are not added automatically, only your entry point.

I'm sorry but Meteor build system doesn't let us use those files :(

**Comment by Deadarius** [comment]
That is correct for new applications, but I wanted to use webpack in the app we already have, I have an entry point that references files from /imports folder. Nevermind /imports folder, I can rename it to anything, but I don't want to rewrite all import statements to use '../../../ etc, it would be nice to be able to specify aliases. Is this a feature you would be interested in assuming I make a PR?

**Comment by Deadarius** [comment]
Any comment on this one?

**Comment by ForsakenHarmony** [comment]
https://github.com/mantrajs/babel-root-slash-import ?
