### ISSUE TITLE
Error when starting in meteor 1.4.1.1

### ISSUE THREAD

**Issue by ansonla3** [thereactivestack/meteor-webpack#281]
ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/anson/meteor-starter-kit
 @ multi main
W20160923-00:59:36.165(8)? (STDERR) /Users/anson/meteor-starter-kit/.meteor/local/build/programs/server/app/server.js:58
W20160923-00:59:36.367(8)? (STDERR)     import '/app/server';                                                 //
W20160923-00:59:36.370(8)? (STDERR)     ^^^^^^
W20160923-00:59:36.370(8)? (STDERR)           
W20160923-00:59:36.371(8)? (STDERR) SyntaxError: Unexpected reserved word
W20160923-00:59:36.371(8)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160923-00:59:36.371(8)? (STDERR)     at /Users/anson/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:287:30
W20160923-00:59:36.372(8)? (STDERR)     at Array.forEach (native)
W20160923-00:59:36.372(8)? (STDERR)     at Function._.each._.forEach (/Users/anson/.meteor/packages/meteor-tool/.1.4.1_1.3462ep++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160923-00:59:36.373(8)? (STDERR)     at /Users/anson/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:128:5

**Comment by jonnyjg** [comment]
Hey ansonla... did you manage to solve this issue in the end? Running into the same issue... a few threads exist here for the issue but no further details.
