### ISSUE TITLE
Where do the bundles live?

### ISSUE THREAD

**Issue by ferhtgoldaraz** [thereactivestack/meteor-webpack#29]
I want to check if the code splits contain what I expect.

I've tried the `profile` webpack config option, but either I didn't use it right or the output is not shown.

I've also found a tool that depends on the webpack's cli `--json` option (that I hope is related to the above's `profile` option) called [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer).

Maybe if I simply look at the bundled files I can find a way to check what I want.

Where/how are the bundles stored, specifically the code splits (chunks)?

Thank you in advance.

**Comment by eXon** [comment]
meteor-webpack is saving the output in memory only (it is much faster than writing on a file).

If you would like to get the infos for code splitting, they are going to be inside the `WebpackStats` global variable. You can [use it with react-router-ssr like this](https://github.com/thereactivestack/kickstart-hugeapp/blob/master/entry/server/entry.js#L7) or you change choose to read it yourself.

**Comment by ferhtgoldaraz** [comment]
Thanks!
