### ISSUE TITLE
Need customizable host

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack#3]
https://github.com/thereactivestack/meteor-webpack/blob/e9681051b2d69cc886d0ee194a01e8040a44b266/plugin/WebpackCompiler.js#L83-L105

I'm developing on a remote dev server, so localhost doesn't work :cry:

**Comment by eXon** [comment]
You can now use devServer in your webpack config. See the kickstart-simple project for how to do it :)
