### ISSUE TITLE
Issues integrating with google-apis-nodejs-client

### ISSUE THREAD

**Issue by john-osullivan** [thereactivestack/meteor-webpack#31]
Hello again,

I've been using the kickstart-hugeapp boilerplate for about a month now with much success, but have now run into an issue with how webpack is loading files.  Based on the errors I'm getting, I can't tell if it's an issue with webpack itself or with this port.

When I add the `google-apis-nodejs-client` library and a json loader, I receive a warning `the request of a dependency is an expression`.  The error is valid, the library has a line `var Endpoint = require(endpointPath);` which tries to generalize past the specific module.  Following that warning, though, a bunch of other libraries start having issues finding core NPM modules.  `fs`, `net`, and `tls` all can't be found once that error gets thrown.  Here's the readout:

![image](https://cloud.githubusercontent.com/assets/3820981/11261339/921039d6-8e41-11e5-8380-b2afe042767b.png)

Do you think the core issue here lies within webpack, or is there a chance that your version has some additional constraints?  Maybe an issue with the config?  Any advice on where to go with this would be much appreciated, thank you!

**Comment by ribbedcrown** [comment]
Hi! I had the same issue with this library. I've solved it by using `meteorhacks:npm`.
Take a look at @eXon`s comment at #26

**Comment by eXon** [comment]
webpack.package.json is not for NPM packages you would like to execute on the server. If it has to run on the server, you have to use meteorhacks:npm. Otherwise, it will try to bundle a Node.js library that cannot be bundled with your code.
