### ISSUE TITLE
Build or Deploy does not find entry

### ISSUE THREAD

**Issue by bensventures** [thereactivestack/meteor-webpack#32]
I have refactored an exiting app to use webpack and all is working well in development. I have somewhat followed the huge-app skeleton organization and configs. The issue comes when I want to deploy or build the app. Running `$ meteor deploy domain.meteor.com` ends up with the following error:

```
While processing files with webpack:webpack (for target web.browser):
entry/client/webpack.conf.js: Entry module not found: Error: Cannot resolve 'file' or 'directory' ./entry in /Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client
resolve file
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry doesn't exist
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry.js doesn't exist
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry.jsx doesn't exist
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry.json doesn't exist
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry.scss doesn't exist
resolve directory
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry doesn't exist (directory default file)
/Users/Ben/Projects/slicedesk/.meteor/local/webpack-npm/entry/client/entry/package.json doesn't exist (directory description file)
```
The same error also shows after this one for the server entry file.

My folder structure is the same as the kickstart apps:
```
.
+-- entry
|    +-- client
|        -- entry.js
|        -- webpack.conf.js
|    +-- server
|        -- entry.js
|        -- webpack.conf.js
|    -- webpack.conf.js
+-- modules
|    ...
```
And an extract of the webpack.conf.js of the client: 
```
module.exports = {
    entry: './entry',
    module: {
        loaders: [
            { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
            { test: /\.js?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
            { test: /\.scss$/, loaders: ["style", "css", "sass"]},
            { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
            { test: /\.(svg|ttf|woff|eot)(\?.*)?$/, loader: 'file' }
        ]
    }
};
```

From another issue in the webpack repo (https://github.com/webpack/webpack/issues/981) it seems this kind of errors could be the result of something unrelated with the actual resolution of the file. The suggested solution there is to run webpack with an option: `webpack --display-error-details`.
I can't however find how to run this in the context of this package. Any pointers? Thanks a lot for the great work on this package :)

**Comment by bensventures** [comment]
I just ran the deploy with the `--allow-incompatible-update` and everything worked :) I was seeing those warnings before the errores mentioned above and never thought it could be related.
```
Installing NPM dependencies for the web bundle...
npm WARN EPEERINVALID sass-loader@3.1.2 requires a peer of webpack@^1.12.6 but none was installed.
Installing NPM dependencies for the server bundle...
npm WARN EPEERINVALID sass-loader@3.1.2 requires a peer of webpack@^1.12.6 but none was installed.
```
I am not entirely sure what is happenning but oh well, as long as I can deploy :)

**Comment by eXon** [comment]
This is because webpack is frozen at 1.12.2 for now. They had a bug in webpack so I had no choice. I'll check if it has been fixed and if so, I'll fix it so your peerDependency doesn't fail :)

**Comment by eXon** [comment]
This should be fixed
