### ISSUE TITLE
[Meteor 1.3] Use NPM packages from Meteor

### ISSUE THREAD

**Issue by bySabi** [thereactivestack/meteor-webpack#34]
Hi @eXon maybe we can search for local npm packages first on `package` folders before than `node_modules`

**Comment by eXon** [comment]
Unfortunally I don't think this is ideal nor needed. What is your use case?

**Comment by bySabi** [comment]
Meteor is in the process to migrate to npm package based aproach.
My  current app is based on package architecture like Telescope, all my local packages go to `packages` folder. I´m planning to create and convert some of this meteor packages on local npm version. But I don´t know where put then. 
On symlink node_modules folder are hundred npm´s and this folder is on .gitignore
I think, maybe, is possible to search package.json npm´s on `packages` folder first for local npm.

Probably it must be implemented on meteor 1.3 build system.

**Comment by eXon** [comment]
I'm already working how we will implement Webpack with Meteor 1.3 beta :)

If I can get rid of webpack.packages.json, you can bet I will do it!

I'll rename this issue and tag it for Meteor 1.3

**Comment by bySabi** [comment]
Good!
if you need testers feel free to ping me.

**Comment by eXon** [comment]
That's great! I'll probably make a branch for early adapters :) I'll keep this issue up-to-date

**Comment by casperanderseneu** [comment]
@eXon I guess you've seen this? https://github.com/meteor/react-packages/pull/151

**Comment by eXon** [comment]
We're going to use NPM pacakges from a real package.json file. No more wrapper in atmosphere! :)

For now there is a few exceptions like react-router or react-helmet because react-router-ssr needs access to it. This is needed until 1.3 is released.
