### ISSUE TITLE
import.css errors

### ISSUE THREAD

**Issue by rhenryjs** [thereactivestack/meteor-webpack#37]
I'm seeing errors with import.css files in both the hugeapp and flowrouter repo's (unmodified):
![](http://puu.sh/m2xhX/8a342a5485.png)

Also a blank page with browser console error: 
![](http://puu.sh/m2xNo/781f932da5.png)

Using Win 7

**Comment by TwinTailsX** [comment]
Just in case it's relevant - this shows up during the install: 
![](http://puu.sh/m47qn/ac64a26449.png)

**Comment by eXon** [comment]
It might be a problem just with Windows. I'll try to get a Windows machine to test this.

**Comment by eXon** [comment]
Should be fixed in the next release
