### ISSUE TITLE
"Promise is not defined" 

### ISSUE THREAD

**Issue by yched** [thereactivestack/meteor-webpack#38]
I'm trying to use the 'promise' package (https://atmospherejs.com/meteor/promise) in a project that also uses 'webpack:webpack'.

But any reference to the Promise object in my server-side code (say, console.log(Promise)) brings a "Promise is not defined" error.
(it seems to be available on the client code, but that's not where I need it)

I can of course add the "promise" npm package to my webpack.packages.json and import it explicitly (import Promise from 'promise'), but then it's the "regular" Promise from https://github.com/then/promise, and not the meteor-aware one from the Meteor package.

So far I didn't seem to have problems accessing other globally available meteor objects (Meteor, underscore...) when using webpack:webpack, but I'm stuck on Promise.

Anything silly I'm forgetting ?

**Comment by yched** [comment]
FWIW, I'm also seeing this behavior in https://github.com/thereactivestack/kickstart-simple

The promise package is present, but any reference to Promise in server-side code brings "Promise is not defined"

Things seem to work fine on a "vanilla" meteor project that doesn't use webpack:webpack, so I'm guessing this is related ?

**Comment by eXon** [comment]
It seems like it could be easily fixed. My guess is you can access Symbol without adding the NPM package (the externals are generated with Meteor exports).

Add this to your server entry file and let me know if it works:

```javascript
import Symbol from 'symbol';
// ...
global.Symbol = Symbol;
```

**Comment by yched** [comment]
Yep, that works.

In my entry file :
```js
import Symbol from 'symbol';
global.Symbol = Symbol;

import './foo.js';
```

In foo.js : 
```js
console.log(Promise);
```

--> outputs :
```
{ [Function: Promise]
  _99: [Function: noop],
  resolve: [Function],
  all: [Function],
  reject: [Function],
  race: [Function],
  denodeify: [Function],
  nodeify: [Function],
  awaitAll: [Function],
  await: [Function],
  async: [Function],
  asyncApply: [Function],
  Fiber:
   { [Function: Fiber]
     yield: [Function],
     current: {},
     poolSize: 120,
     fibersCreated: 3 } }
```
(await, async, Fiber... show it's the correct Promise class enriched by meteor/promise)

Thanks a lot fo the fast reply, @eXon ! Indeed it would probably help if this was automated somehow :-)

**Comment by yched** [comment]
Actually, similar problem, but this time on the client-side, when trying to use meteorhacks:inject-data :

client.entry.js :
```js
Meteor.startup(() => {
  InjectData.getData("redux-initial-state", (data) => {
    console.log(data);
  });
```
--> "InjectData is not defined"

I tried to apply your fix in the client entry file as well, but it doesnt seem to fix that one.
(Like previously, the code above works on a vanilla/non-webpack meteor app)

**Comment by yched** [comment]
Bumped into another one : 
Server-side, with the `import Symbol from 'symbol'; global.Symbol = Symbol;` fix applied,
the EJSON global is not available.

`console.log(EJSON)`
--> EJSON is not defined

In short, webpack:webpack is super cool for accessing npm packages, but as a result it's not always clear how to access the "regular" Meteor libraries ;-)

**Comment by eXon** [comment]
That's weird because you should be able to access any global Meteor global variables. I'll take a deeper look into this.

**Comment by eXon** [comment]
This will be fixed in the next version
