### ISSUE TITLE
load react component module from sibling app?

### ISSUE THREAD

**Issue by citizenkevin** [thereactivestack/meteor-webpack#39]
@eXon 
(hopefully) a quick question for you that has me stuck:

I have a /project folder with 2 meteor apps: /project/app1 and /project/app2.

app1 has the webpack:webpack package installed and it works great. However as soon as I attempt to import a react component from outside the app1 directory (such as /project/app2/appComponent.jsx for instance) I get this error:

**ERROR in ../app2/appComponent.jsx
Module build failed: Error: Couldn't find preset "es2015" relative to directory "path/to/projects/app2"**

I've got a webpack.conf.js in project/app1/client. I've attempted to set resolveLoader.root, but it doesn't seem to work. Or, I'm setting it incorrectly. 

Any suggestions?

Many thanks!

Kevin

**Comment by eXon** [comment]
It depends on your code. When you require code outside of your app folder, it gets weird. The easiest way to deal with that is to make your app2 a package that is inside node_modules.

If you have a symbolic link on projects/app1/node_modules/app2 -> projects/app2, you should be able to `import 'app2/.../;`.

Or even better, you can take your reusable code and put it in a separate shared module :)

**Comment by eXon** [comment]
Another (maybe simplier) option is to create a symbolic link of /projects/app2/node_modules -> /projects/app1/node_modules.

**Comment by citizenkevin** [comment]
@eXon 
Thanks for the tip. Your 2nd suggestion (/projects/app2/node_modules -> /projects/app1/node_modules) did the trick.
Although, I find it a bit disconcerting/frustrating if there isn't a simple way to configure webpack to take care of this. 
I need to more completely learn webpack anyway to refine my setup, but your kickstart-simple and this trick should be enough to get me started.....

Thanks again for the tip!
