### ISSUE TITLE
Wrong line numbers due to cheap-source-maps

### ISSUE THREAD

**Issue by jbbr** [thereactivestack/meteor-webpack#4]
In files containing JSX code and on the server I get wrong file numbers when debugging. This is due to the use of "cheap-source-map" rather then "cheap-module-source-map".

I vote for defaulting to `cheap-eval-module-source-map` for the client- and `cheap-module-source-map` for the server config. This gives almost everytime correct line numbers
Cons: Probably a bit slower rebuilds.

Also the devtool can't be changed for the server - It would be great to add this possibility somehow.

Thanks for this great stack :)

PS: I can add an example and PR if desired.

**Comment by eXon** [comment]
I agree line numbers are important. You can do a PR and I'll look at it.

**Comment by eXon** [comment]
This is fixed

**Comment by jbbr** [comment]
Thanks, sorry for not yet doing a PR.

**Comment by eXon** [comment]
No problem, I was already on the code it was trivial to change :) 

Just to let you know I think I've crashed the whole build when no source map file exists. I'm fixing it right now.

**Comment by eXon** [comment]
Should be fixed now
