### ISSUE TITLE
Is this package removing Meteor.isServer blocks from the client build?

### ISSUE THREAD

**Issue by Sanjo** [thereactivestack/meteor-webpack#40]
Is this package removing code blocks like the following from the client build?

```js
if (Meteor.isServer) {
  // Server only code
}
```

**Comment by eXon** [comment]
It should be. Meteor.isServer will be replaced by true or false and the minifier should get rid of it.

**Comment by Sanjo** [comment]
Cool. Thanks for the quick answer.
