### ISSUE TITLE
Fail when node_modules folder already exists in project

### ISSUE THREAD

**Issue by Sanjo** [thereactivestack/meteor-webpack#41]
When I already have installed npm packages in my project, then webpack fails, because it will not create the symlink to the webpack-npm/node_modules folder (https://github.com/thereactivestack/meteor-webpack/blob/master/plugin/WebpackCompiler.js#L601-L604).

I suggest a stronger check for the symlink that gives the user an error that tells him to move his npm dependencies from package.json to webpack.packages.json and to delete node_modules after he has done it.

This also resolves https://github.com/thereactivestack/kickstart-hugeapp/issues/36 (@tomitrescak).

**Comment by eXon** [comment]
This will be fixed soon because webpack.packages.json is going away for a real package.json file. This is going to be just like Meteor 1.3 :)

**Comment by Sanjo** [comment]
:+1:
