### ISSUE TITLE
babel presets and .babelrc error

### ISSUE THREAD

**Issue by jhartma** [thereactivestack/meteor-webpack#43]
I'd like to use some npm packages like mocha or redux-devtools. Thing is, they need the babel presets set in ```.babelrc``` or ```package.json```. But this gives
```bash
Unknown option: .../app/.babelrc.presets
```
on compile time. 
Any ideas how to get this workgin?

**Comment by eXon** [comment]
What are the presets you need to set? It is easier to set them on the babel settings in your webpack config file

**Comment by eXon** [comment]
For unit testing you can use velocity with mocha unit tests. 

[Here is an example of unit tests with webpack.](https://github.com/thereactivestack/kickstart-simple/blob/master/entry/client/entry.js#L15-L25)

I'm not sure how you could run the unit tests outside Meteor. I've never had that need before.

**Comment by jhartma** [comment]
Thanks for the link. When I set the babel settings in webpack like so
```js
module.exports = {
  entry: "./entry",
  resolve: {
    extensions: [ "", ".js", ".jsx", ".json" ],
    modulesDirectories: [
      "node_modules",
      "modules",
    ],
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: "babel",
        query: {
          plugins: [ "transform-runtime" ],
          presets: [ "es2015" ],
        },
        exclude: [ "node_modules" ],
      },
    ],
  },
}
```
I get 
```bash
Module build failed: ReferenceError: [BABEL] ...client/entry.jsx: Unknown option: direct.presets
```

**Comment by jhartma** [comment]
I figured it out. Just downgraded to babel5 and it works

**Comment by eXon** [comment]
This should not be a problem anymore.
