### ISSUE TITLE
Meteor 1.3 Uncaught ReferenceError: __WebpackDevServerConfig__ is not defined

### ISSUE THREAD

**Issue by djhutch** [thereactivestack/meteor-webpack#47]
I just upgraded to meteor 1.3-modules-beta.2 and started getting the error below. I have the latest version of webpack:webpack (0.4.4). I also tried cloning the kickstart-hugeapp repo and upgrading meteor to this version and get the same error.

```
Uncaught ReferenceError: __WebpackDevServerConfig__ is not defined
    (anonymous function) @ reload.js:23
    maybeReady @ startup_client.js:26
    loadingCompleted @ startup_client.js:32
```

Any idea what is wrong?
Thanks.

**Comment by jiku** [comment]
Same here with [221d8af](https://github.com/meteor/meteor/commit/221d8af44b62b91de50f93077c2b488db4a06dc4).

**Comment by AnnotatedJS** [comment]
Testing with  meteor 1.3-modules-beta.4 webpack works fine. However, testing with  meteor 1.3-modules-beta.5 I get the error message:

Uncaught ReferenceError: __WebpackDevServerConfig__ is not defined

**Comment by eXon** [comment]
I'll be looking into this when I have a few minutes. Probably not hard to fix.

**Comment by eXon** [comment]
meteor-webpack 1.0 will be 100% compatible with Meteor 1.3 :)

**Comment by zaklampert** [comment]
@eXon see https://github.com/mantrajs/kickstart-mantrajs-webpack/issues/1 - I realize this is a community package, but do you know why it wouldn't be working with 1.3?

**Comment by josephdburdick** [comment]
@zaklampert did you try running `meteor run --production` ? It should include the webpack config that's missing.
