### ISSUE TITLE
Building server with target: 'server'?

### ISSUE THREAD

**Issue by Sanjo** [thereactivestack/meteor-webpack#50]
Hi, did you consider that? I got it work and it now uses the core node modules without any polyfills.
I added the following options to entry/server/webpack.conf.js:

```js
target: 'node',
node: {
    console: false,
    global: false,
    process: false,
    Buffer: false,
    __filename: true,
    __dirname: true
}
```

Also I needed to add a lib/meteor.startup.js with:

```js
if (Meteor.isServer) {
  global.require = Npm.require;
}
```

**Comment by eXon** [comment]
This is something I badly wanted. Thank you for figuring it out it will be available on the 1.0 release soon :+1:
