### ISSUE TITLE
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

### ISSUE THREAD

**Issue by grsabreu** [thereactivestack/meteor-webpack#51]
This happened for using `ReactCSSTransitionGroup`, but I can't also use refs.
My JSX is this:

```js
import React from 'react';
import {Link} from 'react-router';
import Helmet from 'react-helmet';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

const SignUpView = React.createClass({
  displayName: 'SignUpView',

  render(){
    return (
      <div className="container container-flow-column full container-flow-full-align">
        <Helmet
        title="Login"
        />

        <h2>New account</h2>
        <ReactCSSTransitionGroup
          transitionName="sign-up-children"
          transitionEnterTimeout={500}
          transitionLeaveTimeout={300}
        >
        {React.cloneElement(this.props.children, {
                    key: this.props.location.pathname
                  })}
        </ReactCSSTransitionGroup>
      </div>
    );
  }
});

export default SignUpView;
```

Doesn't seem to be wrong.
Also doesn't seems there be some React duplicate (`npm ls | grep react`)

**Comment by eXon** [comment]
Do you have the `react-addons-css-transition-group` external set to `React.addons.CSSTransitionGroup`?

**Comment by grsabreu** [comment]
mmm... no.
But the thing is, any code that uses `this.refs` throws that error.
Something like this throws the same error:

```
import React from 'react';

Login = React.createClass({
 handleSubmit(){
  let username = this.refs.username.value;
 },

 render(){
   <form onSubmit={this.handleSubmit}>
         <input ref="username"/>
         <button type="submit">Submit</button>
   </form>
 }
});

export default Login;
```

**Comment by fignuts** [comment]
This is also happening to me. How did you solve it @grsabreu ?

**Comment by gunn** [comment]
I'm having this problem. I think it's caused by having two react versions loaded. One from `.meteor/packages` and the other from `.meteor/local/webpack-npm/package.json`.

Maybe meteor-webpack 1.0 will let us eliminate the former?

**Comment by infacq** [comment]
I'm also having this problem

**Comment by grsabreu** [comment]
The issue was caused by meteor-webpack and meteor not using the same instance of React, after upgrading to the latest meteor-webpack my issue was gone.

**Comment by eXon** [comment]
@infacq Make sure the `react-runtime` package is not within your project. You should get it from NPM :)
