### ISSUE TITLE
Production Build Times

### ISSUE THREAD

**Issue by mxs** [thereactivestack/meteor-webpack#52]
I have a medium sized project.

`meteor build` from fresh checkout (.meteor/local removed) takes around **8 minutes** on my MacBook Pro and **14 minutes** on CircleCI.

Are there anything I should be watching out for in order to reduce the build time. I feel like I'm doing something wrong as these build times seem too long.

**Comment by eXon** [comment]
This will be drastically improved with the 1.0 release of meteor-webpack. If you still feel it is slow, let me know and I'll try my best to konw where we can optimize.

**Comment by mxs** [comment]
I've tried production build in circleci with webpack:webpack 1.0.2 and i'm still getting around 12mins and a little less than that locally. The problem seems like I have to do the following:
-  `meteor build .`
-  `npm install`
-  `meteor build .  ` again

That being said startup time and restarts in development mode have been dramatically improved, much much appreciated! :+1:  :+1:  :+1:

**Comment by eXon** [comment]
@mxs Why do you have to build before doing npm install? If your package.json already got everything, you shouldn't need to do it.

**Comment by mxs** [comment]
Ok thats what I ended up doing in the end and the build time is down to 8min in circleci. Thank you! :smile:
