### ISSUE TITLE
Client reload fails to trigger after any changes saved in the files

### ISSUE THREAD

**Issue by veeramarni** [thereactivestack/meteor-webpack#53]
I'm getting the following error while looking for new changes to reload in the client page. 

```
[HMR] Update check failed: Error: Manifest request to http://localhost:3500/assets/1ac7e473ca1c9f59a5fa.hot-update.json failed.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:3500/assets/web.js:40:23)
```

**Comment by eXon** [comment]
On what OS are you? Do you have a clone of your project or something I can reproduce?

**Comment by veeramarni** [comment]
Sorry for very late response, this happens when i use "[ripple](https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc?hl=en)" emulator only otherwise i don't see this error.

**Comment by veeramarni** [comment]
See the snapshot

![image](https://cloud.githubusercontent.com/assets/3382355/13907812/fedf7504-eecc-11e5-871d-78e757e6b9aa.png)
