### ISSUE TITLE
Status quo for Meteor 1.3 - getting rid of installing NPM

### ISSUE THREAD

**Issue by D1no** [thereactivestack/meteor-webpack#55]
The re-build time can be pretty high because meteor-webpack installs npm along the build process. You already made some hints in the forums about aligning meteor-webpack with meteor's 1.3 npm support.

Any update on this?

**Comment by eXon** [comment]
This is going to be in the 1.0 release :) hopefully in the next week or so

**Comment by D1no** [comment]
Nice! A project is starting next month and I am eager to merge it up with
webpack and Meteor 1.3 :)
On Di., 9. Feb. 2016 at 22:02, Benoit Tremblay <notifications@github.com>
wrote:

> This is going to be in the 1.0 release :) hopefully in the next week or so
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/meteor-webpack/issues/55#issuecomment-182066640>
> .
>
-- 
Send from my Smartphone. Beware spelling and grammar.
-- 
Dino Scheidt
Tel.: +49 (0) 151 2265 6200
Luxemburger Str. 118 | 50939 Cologne | Germany
//Connect with me via LinkedIn.dino-scheidt.de

**Comment by grsabreu** [comment]
Awesome

**Comment by mikesurowiec** [comment]
Really looking forward to it! :+1:

**Comment by eXon** [comment]
Release is going to be march 1st. Meteor 1.3 will be fully supported + npm install out of Meteor!
