### ISSUE TITLE
Webpack 2.x is coming

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack#56]
https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by eXon** [comment]
This is awesome! :) I'm not sure if the coding has even begun but there is a lot of interesting stuff coming up.

**Comment by rclai** [comment]
They've already released a beta version: https://github.com/webpack/webpack/blob/master/package.json

**Comment by eXon** [comment]
I'll be following this closely. There is some huge improvement to come! For now I'm closing this because it is far from being ready.
