### ISSUE TITLE
It weirdly breaks with react-komposer when running in production

### ISSUE THREAD

**Issue by grsabreu** [thereactivestack/meteor-webpack#57]
This is a small reproduction with kickstart-hugeapp

https://github.com/grsabreu/meteor-webpack-komposer-bug

**Comment by grsabreu** [comment]
Here a print of the error
![selection_024](https://cloud.githubusercontent.com/assets/1283200/13197881/e21eb5c6-d7e1-11e5-9e74-6238b4d563df.png)

**Comment by eXon** [comment]
I'm not sure how react-komposer work but this is probably a problem with react-router-ssr. It was orginally made to work with ReactMeteorData but I don't mind adding compatibility. Can you report a bug on [react-router-ssr](https://github.com/thereactivestack/meteor-react-router-ssr/issues) instead?

Thank you

**Comment by grsabreu** [comment]
Ok, you're right. Thanks!
