### ISSUE TITLE
Production code is not minified

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#58]
Even with standardminifier installed the production code is not minified and there is access to all files. Is there anything that should be done in the Webpack part? please, any help is greatly appreciated.

**Comment by eXon** [comment]
That's weird. I'll take a look. Are you using a kickstart project with it?

**Comment by tomitrescak** [comment]
Yes I am. The flow router version.

**Comment by tomitrescak** [comment]
Nevermind. I set "devtool: eval" in my webpack config. Solved.
