### ISSUE TITLE
Webpack dev server public url

### ISSUE THREAD

**Issue by Intel** [thereactivestack/meteor-webpack#61]
I'm trying to run webpack dev server behind a proxy server and having problems with dev server public url. My app is based on 'kickstart-flowrouter' repo.

Here is what I have in my webpack.conf.js:
```javascript
  devServer: {
    host: '192.168.1.100',
    port: 3500,
    public: 'sub.mydomain.com:80'
  },
```

However, the 'public' option doesn't seem to have any effect and in fact if I open compiled server files I see this in reload.js:
```javascript
const devServerOrigin = __WebpackDevServerConfig__.protocol + '//' + __WebpackDevServerConfig__.host + ':' + __WebpackDevServerConfig__.port;
```

I couldn't find where it is generated from but I believe it's problem with meteor-webpack.
Here is what original webpack-dev-server has:
```javascript
var devClient = [require.resolve("../client/") + "?" + protocol + "://" + (options.public || (options.host + ":" + options.port))];
```

So it firstly takes 'public' option and if it doesn't exist it uses host and port. 

Without this option I can't use dev server behind proxy. Unless there is a way to run both meteor and dev server on the same port?

Can someone help me out with this? Thank you

**Comment by Intel** [comment]
I created a pull request https://github.com/thereactivestack/meteor-webpack-reload/pull/1 which fixes this issue

**Comment by eXon** [comment]
I agree this should be supported. I'll review it and make a new release soon.

**Comment by eXon** [comment]
Thanks for the PR!
