### ISSUE TITLE
no place to write customized webpack.conf.js in the new 1.0.1 version?

### ISSUE THREAD

**Issue by beeplin** [thereactivestack/meteor-webpack#62]
happy to see the new 1.0.1 version makes things so simple!

but i found the previous two webpack.conf.js files are missing, and now the only place to write customized config is webpack.json. so the question is, how to bring the conf.js files back?

**Comment by beeplin** [comment]
okay, i tried and found instead of webpack.json, a webpack.conf.js in the same location is all fine. :)

**Comment by eXon** [comment]
If it finds a webpack.config.js it will use it but most people hate those files.

Can you share what's missing in the new way to configure Webpack or it is just that you don't have time to migrate? (I can certainly understand that too)
