### ISSUE TITLE
cannot recognize es6 method syntax when running 'meteor --production'

### ISSUE THREAD

**Issue by beeplin** [thereactivestack/meteor-webpack#63]
`While processing files with webpack:webpack (for target web.browser):`
`client/entry.js: web.js from UglifyJs`
**`Unexpected token punc «(», expected punc «:»`**
`[xxxx.js:106,0]`

i am sure i have all the babel packages installed, and the non-production mode runs okay. but when add `--production`, webpack cannot recognize the new method syntax in es6 (`method() {...}` rather than `method: function() {...}`).

**Comment by eXon** [comment]
This is weird I don't have the problem. Can you share your client/entry.js file and your config file?

**Comment by beeplin** [comment]
it seems not only the npm package `vue-meteor` has this problem, and other packages are all fine. weird. anyway, i can manually modify that file to get it work. thank you!

**Comment by eXon** [comment]
I'm curious why this happens, can you paste your client/entry.js code that was originally crashing?

**Comment by beeplin** [comment]
sorry i've lost the original settings and i didn't have version control since this is just some test code. 
never mind. it might be a very rare edge case. :)
