### ISSUE TITLE
the non-production mode servers assets/web.js from localhost:3500, which cannot be accessed from other computers

### ISSUE THREAD

**Issue by beeplin** [thereactivestack/meteor-webpack#64]
so it's hard to share to other people during the development. is there any possible way to solve this?

**Comment by eXon** [comment]
You can change the devserver host localhost by an ip address so that you can access it externally. Is it what you're looking for?

**Comment by beeplin** [comment]
i added the following into my webpack.conf.js:
`devServer: {
		host: '192.168.199.180'
	},`
which is my local ip. But i got this error when running in my local browser: 
`GET http://192.168.199.180:3500/assets/web.js net::ERR_NETWORK_ACCESS_DENIED`
