### ISSUE TITLE
Starting from scratch doesn't work

### ISSUE THREAD

**Issue by matteodem** [thereactivestack/meteor-webpack#65]
When I run the [following steps](https://github.com/thereactivestack/meteor-webpack/tree/master/packages/webpack#start-from-scratch) locally, node shouts following error to me after executing `npm install`.

```bash
pm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/Matteo/.nvm/versions/node/v4.1.2/bin/node" "/Users/Matteo/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path /Users/Matteo/Projects/meteor/test-apps/test-project/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/Users/Matteo/Projects/meteor/test-apps/test-project/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Matteo/Projects/meteor/test-apps/test-project/npm-debug.log
```

I used Meteor `v1.2.1` and nodejs version `v4.1.2`. So looking forward to trying this out!

**Comment by eXon** [comment]
Have you a package.json file created? It might be missing from the procedure.

Try: `npm init`

**Comment by matteodem** [comment]
oh okay, can you add that to the Start from scratch section? I thought it might be that the webpack packages generates one if not around.

**Comment by eXon** [comment]
Yes I will definitively add the missing step. I'm sorry this step was missing.

**Comment by matteodem** [comment]
Perfect thank you, but `npm init` doesn't help, as in I get following message

```
Please run npm install in your project folder to continue.
```

**Comment by eXon** [comment]
This is not an error but a message ;)

**Comment by matteodem** [comment]
yes I know, but I don't see any guidance as to adding any npm packages to get this to work.
