### ISSUE TITLE
Getting 'Uncaught ReferenceError: Npm is not defined' with Meteor 1.3 and webpack:react

### ISSUE THREAD

**Issue by chompomonim** [thereactivestack/meteor-webpack#66]
I just created fresh meteor 1.3 project where added `webpack:react` and now getting `Uncaught ReferenceError: Npm is not defined` error in browser console.

**Comment by eXon** [comment]
What is your beta version? Can you share the commands you did to start a fresh project?

**Comment by chompomonim** [comment]
$ meteor create --release 1.3-beta.12 webpack-test
$ cd webpack-test
$ meteor
$ meteor remove autopublish
$ meteor remove ecmascript
$ meteor add webpack:webpack
$ meteor add webpack:react
$ meteor
$ npm install
$ metoer

Open browser, type `http://localhost:3000`, look into console and see the error.

**Comment by eXon** [comment]
Damnit I was testing with beta.11 I didn't though beta.12 was out. When you try with 1.3-beta.11 is it working?

**Comment by chompomonim** [comment]
Same error.

Here is my package.json, maybe there is some problem?

```
{
  "name": "webpack-test",
  "private": true,
  "version": "0.0.1",
  "main": "app/server.js",
  "browser": "app/client.js",
  "scripts": {
    "start": "meteor run",
    "test": "meteor test-app --driver-package practicalmeteor:mocha"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "redux": "^3.3.1"
  },
  "devDependencies": {
    "webpack": "^1.12.9",
    "webpack-hot-middleware": "^2.4.1",
    "url-loader": "^0.5.7",
    "file-loader": "^0.8.5",
    "style-loader": "^0.13.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "babel": "^6.3.26",
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.2",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0",
    "redbox-react": "^1.2.0",
    "react-transform-hmr": "^1.0.1",
    "react-transform-catch-errors": "^1.0.0"
  }
}
```

**Comment by bySabi** [comment]
Same error in beta11

**Comment by eXon** [comment]
This is really a weird error. I upgraded a project to Meteor 1.3 instead of creating it from scratch. Maybe this is why I don't crash. I'll try to fix this ASAP.
