### ISSUE TITLE
Package causes excessive disk stats on MacOS X

### ISSUE THREAD

**Issue by FGM** [thereactivestack/meteor-webpack#67]
I previously opened this issue on the Meteor forum, but after more diagnosing, the problem is actually related to this component.
https://forums.meteor.com/t/meteor-constantly-polling-filesystem-120-load-on-inactive-app/18849/2

In short, except with --production, something in webpack (or the dev server) is constantly polling the disk, at around 20000 to 30000 stat() calls per second, instead of using kqueue/fsevents, or polling at a reasonable rate. This appears to be due to the (missing ?) configuration of the chokidar component brought in by watchpack in webpack to abstract filesystem watches.

**Comment by eXon** [comment]
I'll try to find a setting to fix this. This is aweful.

**Comment by FGM** [comment]
Thanks for looking into it. I'd like to help, but not sure how I could debug into this, as the file watcher is not something that the meteor debug plugin opens in: it opens on the main node instance, the one which doesn't do file i/o by default.

**Comment by tomitrescak** [comment]
And this can be related also to the high CPU load as in #70

**Comment by tomitrescak** [comment]
I looked a bit into this issue and I really feel that we should ignore node_modules and .meteor direcotries. It seems that is is possible as mentioned here https://github.com/webpack/watchpack/issues/2

> If you add 
> ignored: /node_modules/, 
> as in this commit b13cefe
> into the chokidar.watch options in DirectoryWatcher.js you get a massive reduction in CPU usage when polling.

So we need somehow is to expose chokidar options.

**Comment by tomitrescak** [comment]
I'm a bit puzzled. I tried to change the watchpack options but it did not seem to affect anything. Then I completely removed ti from the node_modules folder and all still worked. Where does it actually load the watchpack instance from ?

**Comment by tomitrescak** [comment]
OK. After many trials and errors and finally understanding how NPM packages are included in the meteor app. I've chased the correct watchpack and modified the config there. 

The result: My processor is down to **2%** ;)

What I did is that I am ignoring the node_modules and .meteor directories in chokidar.

This is my modified chokidar call in DirectoryWatcher from watchpack

```
this.watcher = chokidar.watch(directoryPath, {
		ignoreInitial: true,
		persistent: true,
		ignored: /(node_modules|\.meteor)/,  // THIS IS WHAT I ADDED
		followSymlinks: false,
		depth: 0,
		atomic: false,
		alwaysStat: true,
		ignorePermissionErrors: true,
		usePolling: options.poll ? true : undefined,
		interval: typeof options.poll === "number" ? options.poll : undefined
	});
```

**Comment by FGM** [comment]
Curious about the loading process: did you find it explained somewhere, or could you give a hint of the process ? I suppose the modules are kept in compiled form somewhere below .meteor/local and not regenerated unless the package.json change ?

**Comment by eXon** [comment]
@tomitrescak Thanks for the tip, I'll try to make some tests.

@FGM For NPM packages Webpack is actually taking care of keeping a cache of your files for hot reload. It's all transparent to Meteor in fact. For Meteor packages they are in .meteor/local compiled.

**Comment by FGM** [comment]
Tested this too : it alleviates the pain by no longer stat-ing .meteor and node_modules indeed, but it only reduces the load to 4-8% on my machine instead of 120%, because it still stats the app files constantly, still making 11000 stat64 calls per second (instead of 20000-30000).

**Comment by tomitrescak** [comment]
Looks like we are getting somewhere;) I think 1% is good iso 120%. I guess we will have to wait until they incorporate the PR for applying the options to watch pack. I'm not sure what can be done until then. Can we repeat all the options that have to be set to reach1%?

**Comment by FGM** [comment]
For me, it took two changes in DirectoryWatcher, to look like this in meteor-webpack 0.4.4:

```javascript
this.watcher = chokidar.watch(directoryPath, {
        ignoreInitial: true,
        persistent: true,
        ignored: /(node_modules|\.meteor)/,  // Tomitrescak: ignore node_modules/ and .meteor/
        followSymlinks: false,
        depth: 0,
        atomic: false,
        alwaysStat: true,
        ignorePermissionErrors: true,
        usePolling: options.poll ? true : undefined,
        interval: typeof options.poll === "number" ? options.poll : 1000 // FGM: poll every second by default
    });
```

The problem, of course, is that I did this by patching the `DirectoryWatcher.js` file in `meteor-webpack/.npm/` manually, and removing the webpack isopack directory, which is not something that we can do as a PR.

**Comment by johanbaath** [comment]
I also have this problem. CPU usage is around 23-26% at all times due to stating a lot of files in the node_modules directory. Is there anything that can be done or can we help out in some way?

**Comment by FGM** [comment]
@johanbaath if you apply the steps I described, does it also drop you back to around 1% or not ?

**Comment by johanbaath** [comment]
@FGM I tried several different things. Adding: `ignored: /(node_modules|\.meteor)/` works as expected and drops my CPU usage down to around 0.5%. It's still polling though, so I tried setting `usePolling` to false which dropped CPU usage to 0.1% without ignoring anything.

Does setting `usePolling` to false have the same effect for you? The best combination for me on OS X seems to be:

```
usePolling: false
ignored: /(node_modules|\.meteor)/
```

You also might want to add `useFsEvents: true` depending on which OS. It defaults to true on OS X.

**Comment by FGM** [comment]
I checked, and it always uses polling, even when adding useFsEvents or setting usePolling to false. Didn't debug why. 
But setting the interval to 1000 instead of undefined gets passed to chokidar AFAICT, and inded load is below 1%, which is good enough to resume work on the project instead of spending more time debugging this.

**Comment by eXon** [comment]
For mac users I've set by default the polling to 1000 (unless you override). Until they add the ignore option, I think it's a good enough solution.
