### ISSUE TITLE
Much slower than normal meteor build

### ISSUE THREAD

**Issue by fignuts** [thereactivestack/meteor-webpack#68]
After installing this plugin I am finding that builds take a lot longer than they used to. Hot reload of react components is very fast but every other change has been slowed down dramatically.

Previously a change to a server file would recompile and reload in ~15 seconds. Now it takes almost a full minute. Is this typical when using this plugin? Have I possibly misconfigured my project in some way?

**Comment by eXon** [comment]
This is probably due to the default sourcemap config. I also think it is way too slow. I'll try what you could tweak to speed things up.

**Comment by eXon** [comment]
Can you try with webpack:webpack 1.0.3 and let me know if it is faster?

**Comment by tomitrescak** [comment]
@exon .. yes significantly for me! It dropped from 40seconds on a large app to around 22. Smaller went down from 20 to around 11 and the toy app is under one second. Impressive ;)

**Comment by gunn** [comment]
@eXon nice! From 5 seconds to 1 second for hot reloads.

**Comment by mxs** [comment]
mine went from 3 secs to 400ms, incredible!

**Comment by fignuts** [comment]
Things are much faster now! Build times are down to ~15 seconds from almost 1 minute. Thanks for this great plugin!
