### ISSUE TITLE
changes in server code doesn't hot reload under 1.0.2

### ISSUE THREAD

**Issue by beeplin** [thereactivestack/meteor-webpack#69]
only client-side code can hot reload.  any changes in server-side code had to take effect by rerunning meteor and waiting looooooog time...
i might do some wrong config? :(

**Comment by eXon** [comment]
You can't have hot-reload on the server. It only works with the client. However, I'm looking into fixing why it takes so much time.

**Comment by beeplin** [comment]
i might be wrong but i thought the original meteor can do server-side hot reload? will check later.

**Comment by beeplin** [comment]
yah i was wrong. turns out that the original meteor doesn't hot reload on server, but simply reboot when server code changes.
