### ISSUE TITLE
I think if you put Npm.require in another package, it will work with absolute paths

### ISSUE THREAD

**Issue by jedwards1211** [thereactivestack/meteor-webpack#7]
I agree that `Npm.require` is incredibly lame in this regard.  As far as I can tell it only has this problem when called from an isobuild plugin, not when called in server code.

Guess what's sillier?  If I remember correctly, calling `Npm.require` through another package **did** work with absolute paths:

```js
NpmWorkaround = {
  require: Npm.require
};
```

```js
Package.onUse(function(api) {
  api.addFiles('NpmWorkaround.js');
  api.export('NpmWorkaround');
});
```

Then in this package, use `NpmWorkaround.require('/abs/path')` instead of `Npm.require('../../.../etc')`.

**Comment by eXon** [comment]
Yea this is definitively smarter than doing ../ 20 times ;) I will try that.

**Comment by jedwards1211** [comment]
I grew to loathe Isobuild after attempting to write a Webpack plugin myself

**Comment by eXon** [comment]
This has been fixed. Thank you for the workaround :+1:
