### ISSUE TITLE
Server always restarts

### ISSUE THREAD

**Issue by gunn** [thereactivestack/meteor-webpack#71]
First, congratulations on the 1.0 release. It's working for my non-trivial app almost out of the box - impressive!

An annoyance though: modifying almost any file in my project results in the server rebuilding and restarting. Even if the modified file isn't included by the server and is not even in the source directory.

Relevant files:

./webpack.json
```json
{ "root": "src/" }
```

./src/server.js
```javascript
if (process.env.NODE_ENV === 'production') {
  var routes = require('routes')
  var store = require('edb').store

  ReactRouterSSR.LoadWebpackStats(WebpackStats)

  store.load()
  ReactRouterSSR.Run(routes)
}
```

I can trigger a server restart with: `touch blahblah.js`

**Comment by eXon** [comment]
The server will restart everytime you change a file that is not within a client folder. This means:

`src/server.js` will trigger a server restart
`src/client.js` will trigger a server restart
`src/lib/collections.js` will trigger a server restart
`src/client/anything.js will hot-reload with no server restart

You just need to make sure your client code is within a client directory. This is unfortunally how Meteor build system is forcing us to work.

**Comment by gunn** [comment]
Ah, pity but okay. There might be some other directories that should be excluded e.g. tests.

**Comment by eXon** [comment]
Yea I know it sucks. It is a restriction of the Meteor build system. Maybe I should look with them for a way to ignore specific folders.

Thanks for the input.
