### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#73]
Wint version 1.0.0 I was able to remove the "react-runtime" and "react-meteor-data" and run only the NPM version. This is no longer the case with the latest, awesomely superfast version, which require that react-runtime is installed. This is not a blocking issue, but something worth looking into. Thanks!

It is easy to reproduce, just remove the runtime from the sample app after you update it to the latest version and referesh the page. Thanks for all the great work!

**Comment by dbismut** [comment]
You need to `import React from 'react'` (or `import React, {Component, PropTypes} from 'react'`  in all your .jsx files. When you render a component, jsx actually translates into `React.createElement`, which doesn't exist if you don't import React.

**Comment by tomitrescak** [comment]
Well, it was working with meteor-webpack 1.0.0 with no issues but it no longer works with 1.0.3. But I will definitelly inverstigate your proposal, makes sense.

**Comment by dbismut** [comment]
I stumbled upon the same issue :)

**Comment by eXon** [comment]
If `webpack:react` was generating `window.React = React;` would it fix your problem?

I think it is required anyway in dev if you want to use the React devtools

**Comment by tomitrescak** [comment]
I think that would be great solution. Also, would help the typescript compiler significantly (not going into details)

**Comment by tomitrescak** [comment]
It does not seem to be the issue with "import React from 'react'" as the error is thrown in web.js when it is actually trying to import react into namespace.

**Comment by eXon** [comment]
In the next release, it will automatically expose React :)

**Comment by tomitrescak** [comment]
Still no luck :(( When I remove react-runtime I get the error at web.js at this line

```
/* 181 */
/***/ function(module, exports) {

	module.exports = React;

/***/ },
```

**Comment by eXon** [comment]
Can you look at your package.json file and let me know if you have the expose-loader in your devDependencies?

**Comment by tomitrescak** [comment]
No I don’t. Is that bad?

**Comment by tomitrescak** [comment]
Actually I DO!!!

**Comment by rravikot** [comment]
@tomitrescak was this resolved for you? I still get this error when I don't use the `react-runtime` package.

**Comment by rravikot** [comment]
I still seem to be getting this issue. It only seems to be working if I use the `react-runtime` package and not if I just want to use the `npm` one.

**Comment by mzugn** [comment]
I can confirm this is indeed an issue. Removing `react-runtime` causes webpack to fail where it tries to `module.exports = React`. I don't really see why this is necessary, I could always just do it myself when I get a hold of React, especially if I use it from npm. Additionally, is there a way to change/augment the webpack config without creating a Meteor package? A kind of merge functionality would be nice, so users can quickly override the config if it's not exposed as a setting in webpack.json.
