### ISSUE TITLE
'.scss' import issue.

### ISSUE THREAD

**Issue by bySabi** [thereactivestack/meteor-webpack#75]
Hi @eXon  I have a issue importing  a '.scss' file.

This is a test repo: https://github.com/bySabi/meteor-1.3_webpack_test
I was triying to port this example to meteor: https://github.com/dennybritz/neal-sample

Right now I'm stuck with this line from file: `src/App/client/index.jsx`
```
...
import "neal-react/css/base.scss";
...
```
This line load `base.scss` from module `neal-react` but fail processing it on line 3 of `node_modules/neal-react/css/base.scss`:
```
...
@import '../node_modules/bootstrap/scss/bootstrap';
...
```

 I guest `sass-loader` not found the path to `../node_modules/bootstrap/...`. Fail with this:

```
ERROR in ./~/css-loader?localIdentName=[name]__[local]__[hash:base64:5]!./~/sass-loader!./~/neal-react/css/base.scss
Module build failed: 
@import '../node_modules/bootstrap/scss/bootstrap';
^
      File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap
Parent style sheet: stdin

```

Any advice on this??

**Comment by eXon** [comment]
The path is not correct because it would look for neal-react/bootstrap/scss/bootstrap.

If the author was using `@import '~bootstrap/scss/bootstrap';` it would work.

I can look to add the includePaths setting so you can at least fix this.

**Comment by bySabi** [comment]
Good! it works with `~bootstrap`. I will make a PR to `neal-react`.

Don´t touch `includePaths` if only for me.

Thanks for your wonderful work :-)

**Comment by bySabi** [comment]
One more thing.

`~` syntax import is only related to `webpack` ?

`neal-react` don´t depend on `webpack`

I have to test it  a little more ...

**Comment by eXon** [comment]
Yea I think it is webpack specific. I don't mind adding the setting (and supporting any node-sass setting) because even if it works out of the box, it's always great to be able to tweak things

**Comment by bySabi** [comment]
Fine!!! tweak it .. please!

:-)

**Comment by bySabi** [comment]
@eXon I fork `webpack:sass` and add `sassLoader` settings with this code:

```
var weight = 300;

function dependencies(settings) {
  return {
    devDependencies: {
      'style-loader' : '^0.13.0',
      'css-loader': '^0.23.0',
      'sass-loader': '^3.1.2',
      'node-sass': '^3.4.2'
    }
  };
}

function config(settings, require) {
  var cssLoader = '';
  var loaders = [];
  var plugins = [];
  var moduleStr = (settings.css && settings.css.module) ? 'module&' : '';
  var path = require('path');
  var CWD = path.resolve('./');

  if (settings.isDebug) {
    if (settings.platform === 'server') {
      cssLoader = 'css/locals?' + moduleStr + 'localIdentName=[name]__[local]__[hash:base64:5]';
    } else {
      cssLoader = 'style!css?' + moduleStr + 'localIdentName=[name]__[local]__[hash:base64:5]';
    }
  } else {
    if (settings.platform === 'server') {
      cssLoader = 'css/locals?' + moduleStr + 'localIdentName=[hash:base64:5]';
    } else {
      var ExtractTextPlugin = require('extract-text-webpack-plugin');
      plugins.push(new ExtractTextPlugin('style.css'));
      cssLoader = ExtractTextPlugin.extract('style', 'css?' + moduleStr + 'localIdentName=[hash:base64:5]');
    }
  }

  if (cssLoader) {
    loaders.push({ test: /\.scss$/, loader: cssLoader + '!sass' });
  }

  return {
    loaders: loaders,
    plugins: plugins,
    extensions: ['.scss'],
    sassLoader: {
      includePaths: [path.join(CWD, 'node_modules')]
    }
  };
}

```

but not work. It gave me ...

```
Failed to load resource: the server responded with a status of 404 (Not Found)      http://localhost:3500/assets/web.js

```

**Comment by eXon** [comment]
The error you're having is because `npm install` now is much smarter at not nesting node_modules folders.

Just released a new version to let you set the includePaths setting like this:

```json
{
  "sass": {
    "includePaths": ["your/folder/here]
  }
}
```

**Comment by bySabi** [comment]
It works with `webpack:sass` 1.0.2 and adding:

```
  "sass": {
    "includePaths": ["./node_modules"]
  }
```

to `webpack.json`

Thanks!!!

**Comment by bySabi** [comment]
I make a repo for anyone who need [neal-sample](https://github.com/dennybritz/neal-sample) ported to meteor 1.3 and webpack

[meteor-neal-sample](https://github.com/bySabi/neal-sample-meteor)
