### ISSUE TITLE
Force full page reload when HMR fails

### ISSUE THREAD

**Issue by tonyxiao** [thereactivestack/meteor-webpack#78]
How do you force an entire page refresh when HMR fails? Right now it just fails silently and requires a manual refresh which can be even less convenient compare to Meteor's full page refresh.

In other words, how do we get the behavior of webpack/hot/dev-server rather than webpack/hot/only-dev-server? (See https://webpack.github.io/docs/hot-module-replacement-with-webpack.html)

PS: Original discussion here https://github.com/kadirahq/mantra/issues/34 but I thought this is a more appropriate place for that particular issue.

**Comment by eXon** [comment]
The behavior you're having ATM is the default behavior most people are using.

If you want the page to reload, you can set: `hotMiddleware.reload` to true in your webpack.json file.

**Comment by tonyxiao** [comment]
Got it. Where in the source code is `hotMiddleware.reload` being handled? I tried to look through the source first but couldn't find anything.

**Comment by eXon** [comment]
You need a webpack.json file in your root directory of your Meteor application. If you have none, just create one like this:

```json
{
  "hotMiddleware": {
    "reload": true
  }
}
```

**Comment by tonyxiao** [comment]
@eXon Sorry I meant where in the `meteor-webpack` source code do you handle this key?

**Comment by eXon** [comment]
This is handled by webpack-hot-middleware.
