### ISSUE TITLE
CLI traces

### ISSUE THREAD

**Issue by mquandalle** [thereactivestack/meteor-webpack#8]
Hi @eXon,

Thank you for this amazing webpack integration, it’s the first one I feel comfortable using. I just want to let you know that webpack leaks some “unexpected” traces for instance in the following command:

```
➜  kickstart-simple git:(master) ✗ meteor build --directory /tmp/kickstart
webpack built ba4cf04d129e674ed435 in 3066ms |
```

Here I normally don’t want to see the “webpack built [...]” line. This is not a super important issue, but I think making `webpack:webpack` completely transparent and integrated with Meteor is a noble goal :-)

**Comment by eXon** [comment]
Webpack compiler is printing this message. I don't think I can disable it and I don't think one little line is a big deal.
