### ISSUE TITLE
webpack:aurelia

### ISSUE THREAD

**Issue by Markusxmr** [thereactivestack/meteor-webpack#80]
Greetings,
Would it be possible to add Aurelia to webpack package?
This is their official webpack configuration, does it help?
[aurelia-skeleton-webpack](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016-webpack)

**Comment by eXon** [comment]
Aurelia seems to be working a lot differently than other frameworks. It needs to load templates and files on the runtime with something like Systemjs. I'll need to take a deeper look at this.

**Comment by Markusxmr** [comment]
Yeah, Aurelia does have some "interesting" internal workings. Hope their (skeleton webpack kit)[https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016-webpack]  is of any help.
Thank you for considering it :smile:

**Comment by eXon** [comment]
I'm closing this because their is no immediate plan to do this unless someone new do a PR.

**Comment by Markusxmr** [comment]
Ok
