### ISSUE TITLE
Typescript options

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#81]
I love that you added such easy typescript support. The thing that puzzles me is why do you override options from tsconfig? No matter what I set e.g. to "modules" options is overridden by your setting. Preferred output is actually "es6" for modules. Is there any way that all options from tsconfig are preserved and you only load default le if no tsconfig exists? 

Thanks!

**Comment by eXon** [comment]
Should be fixed in `webpack:typescript@1.0.1`. I'm not used to TypeScript config so I wasn't sure what was suppose to be fixed or not. Maybe I should start using it with more projects xD
