### ISSUE TITLE
configure dev to something other than localhost?

### ISSUE THREAD

**Issue by mwaschkowski** [thereactivestack/meteor-webpack#82]
Hi,

I've updated my webpack.json like so:

{
  "root": "src",
  "devServer": {
    "host": "meteorwebpack-xxx.c9users.io"
  }
}

but the app still starts with localhost. Running meteor --port 8080

What is the proper way to configure it to not use localhost?

Thanks,

Mark

**Comment by eXon** [comment]
Your Meteor server and the devServer are two different things. If you want to change the URL meteor is using, you can set the environment variable ROOT_URL to anything you would like.

**Comment by mwaschkowski** [comment]
OK, great, worked like a charm. Now is there are simple answer how to get
node to run on a different port as well? I am working on the c9.io cloud
environment so modify some of the parameters as they control those
settings...

Thanks,

Mark

**Comment by eXon** [comment]
For the Meteor server you can set the environement variable PORT and for webpack dev server you can set `devServer.porrt`.

**Comment by mwaschkowski** [comment]
OK, thanks, I'll give that a try!

Mark
