### ISSUE TITLE
webpack blaze with jade support ?

### ISSUE THREAD

**Issue by crapthings** [thereactivestack/meteor-webpack#83]
- [x] webpack coffeescript
- [x] webpack stylus
- [ ] webpack jade

**Comment by eXon** [comment]
I'll add it to my todo list of loaders to support :)

**Comment by crapthings** [comment]
there're two jade packages that support jade

https://github.com/mquandalle/meteor-jade

https://github.com/dalgard/meteor-viewmodel

but the first one doesn't seems to support viewmodel2

https://forums.meteor.com/t/viewmodel-2-a-new-level-of-simplicity/13581/11

**Comment by avalanche1** [comment]
+1 for https://github.com/dalgard/meteor-jade
It has more features

**Comment by eXon** [comment]
If you want to use Jade with Meteor, you can add the package and also use Webpack. They are not incompatible.

However, if you want to be able to import Jade files, you can now use `webpack:jade`.

**Comment by avalanche1** [comment]
`webpack:jade` - what transpiler does it use? mquandale or dalgard? (or maybe I don't understand and it works a whole way differently :smile: )

**Comment by avalanche1** [comment]
Ahhhj... so there is no `webpack:blaze` - does it work out of the box?

**Comment by eXon** [comment]
Yes you can use Blaze by using the package and .html files anywhere.
