### ISSUE TITLE
i can't not download this package ?

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#85]
i tried to download this package and this error: 

```
 Errors prevented startup:

   While downloading webpack:webpack@1.0.8...:
   error: read ECONNRESET

=> Your application has errors. Waiting for file change.
```
from 77%, 90%, it hang and die.

 i tried 2 days but still not work. anyone help ?

**Comment by eXon** [comment]
This is weird. You're adding it as a Meteor package and not an NPM package right?

**Comment by lyquocnam** [comment]
no, it is meteor package: 
https://github.com/thereactivestack/meteor-webpack/tree/master/packages/webpack/
it the same as i upgrade meteor to 1.3 beta 16 or add package...
the problem is my downline ?
