### ISSUE TITLE
Error in your package.json

### ISSUE THREAD

**Issue by avalanche1** [thereactivestack/meteor-webpack#86]
If smth's wrong with `package.json` app just exits :scream: with `Process finished with exit code 1`.
Can you make it that it acts the way meteor handles compile-time errors: wait for corrections in file, instead of exiting the process?

**Comment by avalanche1** [comment]
Same goes for any error happening at webpack-build time.

**Comment by eXon** [comment]
Yea I know about that but I though it was not a big deal. I'll need to remove package.json from the Node.js filesystem cache. I'll take a look when I have some time.

**Comment by avalanche1** [comment]
On my setup (meteor 1.2) it takes about 90 secs to restart which is frustrating at best

**Comment by eXon** [comment]
90 secs is not a normal speed for a server restart. Do you have a huge project?

**Comment by avalanche1** [comment]
Nope, the opposite.
Don't know, what could be the cause. 
I currently work on meteor 1.1 and have decided to give a try to webpack's HMR, but there were so many issues (coffeescript and other stuff), so I'll give it a spin when I've moved to 1.3 after I launch my app.
In the meanwhile, closing this.
