### ISSUE TITLE
Cannot access global object in entry file

### ISSUE THREAD

**Issue by avalanche1** [thereactivestack/meteor-webpack#87]
So if I define collections in entry file in coffee:
`@Cats = new Mongo.Collection('categories')`
it throws `TypeError: Cannot set property 'Cats' of undefined`

**Comment by eXon** [comment]
Have you tried global.Cats?

Why do you need to use the global scope if you can now import files? Can you with CoffeeScript?

**Comment by avalanche1** [comment]
I don't know, maybe I'm not sure how to work with import.
I'm used to declaring global vars in CS + Meteor... I guess, there's another approach at work here?

**Comment by eXon** [comment]
I don't know the CoffeeScript syntax for this but instead of using global variables, it is always better to import variables from specific files like this:

```javascript
import BlogPost from './collections/BlogPost';
```

I don't know if CoffeeScript support this syntax.

**Comment by avalanche1** [comment]
Well, I can always escape pure-js syntax in CS.
Still strange, that `this` doesnt work with webpack...

**Comment by eXon** [comment]
Global variables should not be the default usage with Webpack. If you're still having troubles, let me know!
