### ISSUE TITLE
Adding a custom loader

### ISSUE THREAD

**Issue by swennemans** [thereactivestack/meteor-webpack#88]
Is is possible to add a customer loader without rewriting the whole `webpack.config.js`?

My specific usecase: 
I'm using postCSS, however Webstorm doesn't like nesting in CSS files. Therefore I would give these files a .less extension, and process them with Webpack as CSS. 

Like so:
```
 {
      test: /\.less$/,
      loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader')
 }
```

Or should I in this case write a custom`webpack.config.js`?
Thanks!

**Comment by eXon** [comment]
I really need to get post-css to work with less / sass / anything. Would it fix your problem?

The problem with a json file is we cannot use regex, so we can't just put it in webpack.json.

**Comment by swennemans** [comment]
For me personally that would fix the problem.

Is there any example file available on how an custom `webpack.config.js` would look like?

**Comment by eXon** [comment]
You can update all your webpack packages and postcss will be automatically added to less, sass or stylus :)

**Comment by infacq** [comment]
is there any example for custom loader

**Comment by eXon** [comment]
@infacq you can't just choose your custom loader. You either use a Meteor webpack package or you can make one yourself (just look at the existing ones).
