### ISSUE TITLE
Integrate with Meteor "prod"/"dev" mode

### ISSUE THREAD

**Issue by mquandalle** [thereactivestack/meteor-webpack#9]
Hi @eXon,

You rely on the `NODE_ENV` variable to detect either the application is in production mode or not, you also indicates in the README that you would prefer to integrate with the Meteor mode which sounds like the right thing to do to me.

I believe this should be simple enough using the option argument of the `processFilesForBundle` method as does the `standard-minifiers` package for instance: https://github.com/meteor/meteor/blob/6203983692920a33370e8e1f2717d7bd2884a451/packages/standard-minifiers/plugin/minify-js.js#L11

**Comment by eXon** [comment]
This is exactly what I would love to do. I tried a few things with MinifyPlugin but I failed to find a way. I asked the Meteor team if their is a way and if their is not, I'll do a PR to isobuild.

**Comment by mquandalle** [comment]
But isn’t `options.minifyMode` enough?

**Comment by eXon** [comment]
It is not available inside the Compiler and the Minifier is running after. When you are inside a Minifier, you don't have the individual files but the bundle of everything. I'm sure I'll find a way because I would rather rely on Meteor than a environment variable.

**Comment by mquandalle** [comment]
Oh yes, sorry I confused the minifier and the compiler APIs...

**Comment by eXon** [comment]
You can follow https://github.com/meteor/meteor/pull/5448 for when the buildMode will be available to compilers :)

**Comment by eXon** [comment]
This is fixed in 0.2.0 :)
