### ISSUE TITLE
how to import bootstrap (sass, less, stylus) ?

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#90]
i tried with many types but still can not import bootstrap.

in my less file:
`@import "~/node_modules/bootstrap-less/bootstrap/bootstrap.less";`
or
`@import "~/node_modules/bootstrap/bootstrap/bootstrap.less";`
or
`@import "bootstrap/less/bootstrap.less";`

tried with other sass, and stylus too and make sure i already have webpack:stylus, webpack:less, webpack:sass and npm dependencies.

` Cannot resolve 'file' or 'directory'`

i use meteor 1.3 beta.11 ( beta.16 bug right now )

**Comment by lyquocnam** [comment]
i try to change import path to:

`import '!bootstrap-styl/bootstrap/index.styl';`
and error:
```
in ./~/bootstrap-styl/bootstrap/index.styl
Module parse failed: D:\DEV\Meteor\webpack\node_modules\bootstrap-styl\bootstrap\index.styl Line 8: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| // Core variables and mixins
| @import "bootstrap/variables"
| @import "bootstrap/mixins"
| 
 @ ./client/modules/core/components/Layout.jsx 19:0-47
```

any missing ?

**Comment by eXon** [comment]
In your less file you can do:
```less
@import "~bootstrap/less/bootstrap.less";
```
Or with the code you can do:
```js
import 'bootstrap/less/bootstrap';
```

**Comment by lyquocnam** [comment]
awesome ! this work, great, thanks @eXon the best package !!
