### ISSUE TITLE
issue deploying on heroku

### ISSUE THREAD

**Issue by cj** [thereactivestack/meteor-webpack#91]
Evening.  First off, thank you for meteor-webpack, it is just what I've been looking for :)

So I'm trying to push to production using https://github.com/c0cky/meteor-buildpack-horse to heroku.  I'm just pushing the https://github.com/thereactivestack/kickstart-meteor-react-router example after running  meteor update --release 1.3-beta.16.  I'm getting this error: https://gist.github.com/8cf3a832a56e4dc77389

Is there something I'm missing?

**Comment by eXon** [comment]
This is weird. I'll take a look asap.

**Comment by eXon** [comment]
What are the packages you are using in your project?
