### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by jakobloekke** [thereactivestack/meteor-webpack#92]
I'm getting an error when trying to use async/await syntax in a package:
`ReferenceError: Promise is not defined at callInvokeWithMethodAndArg (node_modules/meteor/babel-runtime/node_modules/regenerator/runtime.js:182:1)`

If I try to use the package in a vanilla Meteor 1.3beta project, I don't get this error, so maybe it's someting with the meteor-webpack package?

**Comment by eXon** [comment]
What browser / OS are you using?

**Comment by jakobloekke** [comment]
It's a serverside error. I'm using OSX 10.11.3.

**Comment by eXon** [comment]
I've added the Meteor polyfill for Promise. Shouldn't be a problem with 1.0.9
