### ISSUE TITLE
[mantra + webpack] How to seperate module styles ( css, less, sass, styl...) ?

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#93]
i tried with mantra modules but not seperate.
i have 2 modules: admin module + home module.
i want home module has some styles and admin module has some other styles. And 2 modules import from 1 base styles.
how can i do that ?
currently, my home module loaded styles, others module have same styles. i'm sure in admin module i was none style files.

**Comment by eXon** [comment]
There is many ways to do that.

The easiest way to do that would be to add a class at the beginning of your code with LESS or SASS:

```less
.home-app {
   h1 { color: red; }
}

.admin-app {
  h1 { color: blue; }
}
```

You can also use local CSS ([read more about that here](https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284)).

**Comment by lyquocnam** [comment]
ya i using this way for now, but App will load all stylesheet right ?
if it is true, that's not good idea! we can try any better ?
sorry, i think this is Mantra problem !
thanks mr @eXon !

**Comment by eXon** [comment]
Their is no way to split your generated CSS file ATM. Meteor is using a single global one.

**Comment by lyquocnam** [comment]
thanks @eXon
