### ISSUE TITLE
build for web.browser too long

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#95]
build at the fist time run webpack too long.
`webpack built 7701a109ed5bb0761e2c in 64233ms-`

**Comment by eXon** [comment]
Please provide the relevant information to help you. This is not a bug report.

**Comment by lyquocnam** [comment]
ya, i dont known how, but it really so long to build.
i start:
`meteor`
it will run
```
...
Building for web.browser
```
and done with
`webpack built 7701a109ed5bb0761e2c in 64233ms-`
often 60 seconds -> 70 seconds.
if we can speed up, that's good !
thanks mr @eXon !

**Comment by lyquocnam** [comment]
yes ! i tried with this babel plugin, it more speed up:
http://babeljs.io/docs/plugins/transform-eval/
`webpack built 907f6eb48219975fa5ba in 24948ms-`
24 seconds.
but i don't know have any problems, i will watching...
