### ISSUE TITLE
can we global React variabe ?

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#96]
can we global React variabe without import in each component ?
can we do with stateless too ?

thanks for help !

**Comment by eXon** [comment]
The React global variable is always defined with `webpack:react`. You do not need to import it everywhere.

**Comment by lyquocnam** [comment]
i try to remove from ProductForm Component:
`import React from 'react';`

```
ProductForm.jsx?3733:154 
Uncaught ReferenceError: React is not defined
```

**Comment by eXon** [comment]
@lyquocnam have you tried updating webpack:webpack and webpack:react?

**Comment by lyquocnam** [comment]
i think i using lastest version of these packages:
`webpack:assets@1.0.0
webpack:core-config@1.0.0
webpack:css@1.0.1
webpack:less@1.0.0
webpack:npmworkaround@1.0.0
webpack:react@1.1.2
webpack:reload@1.0.0
webpack:webpack@1.0.8`

**Comment by lyquocnam** [comment]
@eXon  i remove React-runtime and React is required.
did webpack:react work exactly ?

i checked lastest webpack releases
